// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.Plan;

/************************************************************/
/**
 * 
 */
public class ComparisonView {
	/**
	 * 
	 */
	private Plan plan1;
	/**
	 * 
	 */
	private Plan plan2;
};
