// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;


import edu.kit.informatik.studyplan.client.model.system.ProposalInformation;
import edu.kit.informatik.studyplan.client.view.components.WizardComponent;

/************************************************************/
/**
 * 
 */
public class GenerationWizardComponent1 extends WizardComponent {
	/**
	 * 
	 */
	private Plan plan;
	/**
	 * 
	 */
	private ProposalInformation information;

	/**
	 * 
	 * @return  
	 */
	public WizardComponent next() {
		return null;
	}

	/**
	 * 
	 */
	public void onChange() {
	}
};
