// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.modules.Module;
import edu.kit.informatik.studyplan.client.view.components.ModuleBox;

/************************************************************/
/**
 * Klasse, welche die Modul-Informations-Sidebar kapselt.
 */
public class ModuleInfoSidebar {
    /**
     * Modul, welches angezeigt werden soll
     */
    private Module module;
    /**
     * Die ModuleBoxen, welche als Abhängigkeiten angezeigt werden.
     */
    private Collection<ModuleBox> moduleBox;

    /**
     * Methode, die beim Schließen der ModuleInfoSidebar aufgerufen wird.
     */
    public void onClose() {
    }

    /**
     * Methode, die bei Veränderungen des Moduls aufgerufen wird (notwendig
     * wegen dynamischem Laden des Moduls).
     */
    public void onChange() {

    }
    /**
     * Methode, die bei einer Veränderung der Daten aus dem Modell aufgerufen
     * wird. Dies kann insbesondere dann wichtig sein, wenn das laden der Daten
     * zu einem Modul länger dauert.
     */
};
