// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import java.lang.reflect.Method;

import edu.kit.informatik.studyplan.client.model.system.SearchLazyLoadingCollection;
import edu.kit.informatik.studyplan.client.view.components.ModuleFilter;
import edu.kit.informatik.studyplan.client.view.components.ModuleList;

/************************************************************/
/**
 * 
 */
public class ModuleFinder {
	/**
	 * 
	 */
	private SearchLazyLoadingCollection lazyLoadingModuleCollection;
	/**
	 * 
	 */
	private boolean isSidebar;
	/**
	 * 
	 */
	private ModuleFilter moduleFilter;
	/**
	 * 
	 */
	private ModuleList moduleList;
	/**
	 * 
	 */
	private boolean isPreferencable;
	/**
	 * 
	 */
	private Method isPlaced;

	/**
	 * 
	 */
	public void onScroll() {
	}

	/**
	 * 
	 */
	public void onSearch() {
	}

	/**
	 * 
	 */
	public void onChange() {
	}
};
