// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.FilterComponent;

/************************************************************/
/**
 * 
 */
public class ModuleFilter {
	/**
	 * 
	 */
	private FilterComponent filterComponent;

	/**
	 * 
	 */
	public void onSearch() {
	}
};
