// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.system.SimpleModuleCollection;
import edu.kit.informatik.studyplan.client.view.components.ModuleBox;

/************************************************************/
/**
 * 
 */
public class ModuleList {
	/**
	 * 
	 */
	private SimpleModuleCollection modules;
	/**
	 * 
	 */
	private ModuleBox[] moduleBox;
	/**
	 * 
	 */
	private boolean isPreferencable;
};
