// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.modules.Module;

/************************************************************/
/**
 * Diese Klasse repräsentiert eine einzelne Box, welche ein Modul darstellt
 */
public class ModuleBox {
    /**
     * Das darzustellende Modul
     */
    private Module module;
    /**
     * Ob das Modul entfernbar ist
     */
    private boolean isRemovable;

    /**
     * Möglichkeit einen roten Rand um das Modul zu setzten
     * 
     * @param setBorder
     *            Ob der Rahmen gesetzt werden soll (true) oder nicht (false)
     */
    public void setRedBorder(final boolean setBorder) {
    }

    /**
     * Methode, welche das Modul entfernt
     */
    public void removeModule() {
    }

    /**
     * Methode, welche beim Klick auf das Modul ausgeführt wird.
     */
    public void click() {
    }
};
