// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.modules.Module;
import edu.kit.informatik.studyplan.client.view.components.ModuleBox;

/************************************************************/
/**
 * 
 */
public class ModuleInfoSidebar {
	/**
	 * 
	 */
	private Module module;
	/**
	 * 
	 */
	private ModuleBox[] moduleBox;

	/**
	 * 
	 */
	public void onChange() {
	}
};
