// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.modules.Module;

/************************************************************/
/**
 * 
 */
public class ModuleBox {
	/**
	 * 
	 */
	private Module module;
	/**
	 * 
	 */
	private boolean isRemovable;

	/**
	 * 
	 */
	public void setRedBorder() {
	}

	/**
	 * 
	 */
	public void removeModule() {
	}

	/**
	 * 
	 */
	public void click() {
	}
};
