// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.system.NotificationCollection;
import edu.kit.informatik.studyplan.client.view.components.NotificationBox;

/************************************************************/
/**
 * 
 */
public class NotificationCentre {
	/**
	 * Wird mittels NotificationCollection.getInstance() geladen.
	  * MainView ist ein Observer der NotificationCollection und zeigt neue Notifications ggf. an.
	 */
	private NotificationCollection notificationCollection;
	/**
	 * 
	 */
	private NotificationBox notificationBox;

	/**
	 * 
	 */
	public void onChange() {
	}
};
