// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.system.Notification;

/************************************************************/
/**
 * 
 */
public class NotificationBox {
	/**
	 * 
	 */
	private Notification notification;

	/**
	 * 
	 */
	public void onClose() {
	}

	/**
	 * 
	 */
	public void blurOut() {
	}
};
