// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.user.Student;
import edu.kit.informatik.studyplan.client.view.components.Semester;

/************************************************************/
/**
 * Plan der bestandenen Module
 */
public class PassedModulePlan {
    /**
     * Der Student, der die Module bestanden hat
     */
    private Student student;
    /**
     * Die Semster, in welche die bestandenen Module geordnet sind.
     */
    private Semester[] semester;
};
