// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.user.Student;
import edu.kit.informatik.studyplan.client.view.components.Semester;

/************************************************************/
/**
 * 
 */
public class PassedModulePlan {
	/**
	 * 
	 */
	private Student student;
	/**
	 * 
	 */
	private Semester[] semester;
};
