// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.plans.Plan;

/************************************************************/
/**
 * 
 */
public abstract class PlanHeadBar {
	/**
	 * 
	 */
	private Plan plan;

	/**
	 * 
	 */
	public void onChange() {
	}
};
