// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.plans.Plan;

/************************************************************/
/**
 * Klasse welche ein Element einer PlanList kapselt
 */
public class PlanListElement {
    /**
     * Der Plan, welcher angezeigt werden soll
     */
    private Plan plan;

    /**
     * Methode, welche beim Klick auf "anzeigen" aufgerufen wird
     */
    public void show() {
    }

    /**
     * Methode, welche beim Klick auf "exportieren" aufgerufen wird
     */
    public void export() {
    }

    /**
     * Methode, welche beim Klick auf "duplizieren" aufgerufen wird
     */
    public void duplicate() {
    }

    /**
     * Methode, welche beim Klick auf "löschen" aufgerufen wird
     */
    public void delete() {
    }
};
