// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.plans.PlanCollection;

/************************************************************/
/**
 * 
 */
public class PlanList {
	/**
	 * 
	 */
	private PlanCollection planCollection;

	/**
	 * 
	 */
	public void onActionSelection() {
	}

	/**
	 * 
	 */
	public void onChange() {
	}
};
