// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.plans.Plan;

/************************************************************/
/**
 * 
 */
public class PlanListElement {
	/**
	 * 
	 */
	private Plan plan;

	/**
	 * 
	 */
	public void show() {
	}

	/**
	 * 
	 */
	public void export() {
	}

	/**
	 * 
	 */
	public void duplicate() {
	}

	/**
	 * 
	 */
	public void delete() {
	}
};
