// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.Semester;

/************************************************************/
/**
 * Klasse, welche die Ansicht des Studienplans kapselt
 */
public class Plan {
    /**
     * Die Semster des Plans
     */
    private Semester[] semester;
    /**
     * Das Modell-Objekt des Plans
     */
    private edu.kit.informatik.studyplan.client.model.plans.Plan plan;
    /**
     * Die Ausrichtung des Studienplans: Normalerweise links, im Fall des
     * Vergleichs aber auch rechts.
     */
    private String align;

    /**
     * Methode zum hinzufügen neuer Semester
     */
    public void addSemester() {
    }

    /**
     * Methode, welche bei Änderungen des Plans aufgerufen wird, und welche auch
     * die onChange() Methoden der Semester aufruft.
     */
    public void onChange() {
    }
};
