// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.Semester;

/************************************************************/
/**
 * 
 */
public class Plan {
	/**
	 * 
	 */
	private Semester[] semester;
	/**
	 * 
	 */
	private Plan plan;
	/**
	 * Die Ausrichtung des Studienplans: Normalerweise links, im Fall des Vergleichs aber auch rechts.
	 */
	private String align;

	/**
	 * 
	 */
	public void addSemester() {
	}

	/**
	 * 
	 */
	public void onChange() {
	}
};
