// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

/************************************************************/
/**
 * 
 */
public class ProposalSidebar {

	/**
	 * 
	 */
	public void delete() {
	}

	/**
	 * 
	 */
	public void save() {
	}

	/**
	 * 
	 */
	public void saveAs() {
	}
};
