// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.PlanHeadBar;

/************************************************************/
/**
 * Kopfzeile, welche angezeigt wird, wenn ein vorgeschlagener Plan angezeigt
 * wird
 */
public class ProposedHeadBar extends PlanHeadBar {
};
