// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.FilterComponent;

/************************************************************/
/**
 * Filter, welcher durch die Auswahl eines Bereichs aktiviert wird
 */
public class RangeFilter extends FilterComponent {
    /**
     * Das Minimum des auswählbaren Bereichs
     */
    private int min;
    /**
     * Das Maximum des auswählbaren Bereichs
     */
    private int max;

    /**
     * Methode welche bei der Auswahl eines Filterobjekts ausgeführt wird
     */
    public void onSelect() {
    }
};
