// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.FilterComponent;

/************************************************************/
/**
 * 
 */
public class RangeFilter extends FilterComponent {
	/**
	 * 
	 */
	private int min;
	/**
	 * 
	 */
	private int max;

	/**
	 * 
	 * @return  
	 */
	public String getParams() {
		return null;
	}

	/**
	 * 
	 */
	public void onSelect() {
	}
};
