// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.PlanHeadBar;

/************************************************************/
/**
 * 
 */
public class RegularHeadBar extends PlanHeadBar {

	/**
	 * 
	 */
	public void generate() {
	}

	/**
	 * 
	 */
	public void verify() {
	}

	/**
	 * 
	 */
	public void rename() {
	}
};
