// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.view.components.PlanHeadBar;

/************************************************************/
/**
 * Kopfzeile welche angezeigt wird, wenn ein regulärer Plan angezeigt wird
 */
public class RegularHeadBar extends PlanHeadBar {

    /**
     * Methode, welche die Generierung eines neuen Plans anstößt
     */
    public void generate() {
    }

    /**
     * Methode, welche die Verifizierung eines neuen Plans anstößt
     */
    public void verify() {
    }

    /**
     * Methode, welche die Umbenennung eines Plans ausführt
     */
    public void rename() {
    }
};
