// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import java.awt.Event;

import edu.kit.informatik.studyplan.client.view.components.ModuleBox;

/************************************************************/
/**
 * 
 */
public class Semester {
	/**
	 * 
	 */
	private Semester moduleCollection;
	/**
	 * 
	 */
	private ModuleBox[] moduleBox;
	/**
	 * Die Ausrichtung des Studienplans: Normalerweise links, im Fall des Vergleichs aber auch rechts.
	 */
	private String align;

	/**
	 * 
	 */
	public void removeSemester() {
	}

	/**
	 * 
	 * @param event 
	 * @param ui 
	 */
	public void onDrop(Event event, Object ui) {
	}

	/**
	 * 
	 */
	public void scrollLeft() {
	}

	/**
	 * 
	 */
	public void scrollRight() {
	}
};
