// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.user.Student;
import edu.kit.informatik.studyplan.client.view.components.WizardComponent;

/************************************************************/
/**
 * 
 */
public class SignUpWizardComponent1 extends WizardComponent {
	/**
	 * 
	 */
	private Student student;

	/**
	 * 
	 * @return  
	 */
	public WizardComponent next() {
		return null;
	}

	/**
	 * 
	 */
	public void onChange() {
	}
};
