// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

import edu.kit.informatik.studyplan.client.model.user.Student;
import edu.kit.informatik.studyplan.client.view.components.WizardComponent;

/************************************************************/
/**
 * Klasse, welche die erste Seite des Registrierungs-Wizards kapselt
 */
public class SignUpWizardComponent1 extends WizardComponent {
    /**
     * Der Student, der sich registriert
     */
    private Student student;

    /**
     * Gibt ein Objekt vom Typ SignUpWizardComponent2 zurück
     * 
     * @return Objekt vom Typ SignUpWizardComponent2 (zweite Seite des Wizards)
     */
    public WizardComponent next() {
        return null;
    }

    /**
     * Methode, welche bei Veränderungen des Seiteninhalts aufgerufen wird.
     */
    public void onChange() {
    }
};
