// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components;

/************************************************************/
/**
 * 
 */
public abstract class WizardComponent {

	/**
	 * 
	 * @return  
	 */
	public abstract edu.kit.informatik.studyplan.client.view.components.WizardComponent next();
};
