// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification.standard;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;
import edu.kit.informatik.studyplan.server.verification.VerificationResult;
import edu.kit.informatik.studyplan.server.verification.Verifier;

/************************************************************/
/**
 * Der StandardVerifier importiert den Verifier. Er ist eine konkret
 * verifizierende Klasse.
 */
public class StandardVerifier implements Verifier {

	public VerificationResult verify(Plan plan) {
		return null;
	}
};
