// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.view.components.uipanel.ComparisonView;

/************************************************************/
/**
 * Klasse, welche die Vergleichsseite kapselt
 */
public class ComparisonPage {
    /**
     * Das ComparisonView Element, welches angezeigt wird
     */
    private ComparisonView comparisonView;
};
