// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import backbone.BackboneModel;

/************************************************************/
/**
 * Ein Model, welches in einem Cookie gespeichert wird (Erweitert von
 * Backbone.Model)
 */
public abstract class CookieModel {
    /**
     * Die Synchronisierungs-Methode, welche das Model-Objekt in einem Cookie
     * speichert
     */
    private Object sync;
};
