// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

/************************************************************/
/**
 * Dieses Singleton wird als Event-Bus zwischen verschiedenen Komponenten der
 * Applikation verwendet. Jedes Objekt kann mittels getInstance() auf den
 * EventBus zugreifen und sich als Listener registrieren oder einen Event
 * auslösen.<br>
 * Ein Beispiel für einen solchen Event wäre die Anzeige eines Moduls in der
 * Seitenleiste beim Klick auf das Modul. (Erbt von Backbone.Event)
 */
public class EventBus {
    /**
     * Die Instanz des Event-Busses
     */
    private static edu.kit.informatik.studyplan.client.model.system.EventBus instance;

    /**
     * Methode zum erhalten einer Instanz des Event Busses
     * 
     * @return Die Event-Bus Instanz
     */
    public static edu.kit.informatik.studyplan.client.model.system.EventBus getInstance() {
        return null;
    }
};
