// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

/************************************************************/
/**
 * Erbt von Backbone.EventBeispiele für Events: Modul soll angezeigt werden
 */
public class EventBus {
	/**
	 * 
	 */
	private static edu.kit.informatik.studyplan.client.model.system.EventBus instance;

	/**
	 * 
	 * @return  
	 */
	public edu.kit.informatik.studyplan.client.model.system.EventBus getInstance() {
		return null;
	}
};
