// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.system.Filter;
import edu.kit.informatik.studyplan.client.model.system.OAuthCollection;

/************************************************************/
/**
 * Eine Collection von Filtern
 */
public class FilterCollection extends OAuthCollection {
    /**
     * Die Filter der Collection
     */
    private Collection<Filter> filter;
};
