// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.Filter;
import edu.kit.informatik.studyplan.client.model.system.OAuthCollection;

/************************************************************/
/**
 * 
 */
public class FilterCollection extends OAuthCollection {
	/**
	 * 
	 */
	private Filter[] filter;
};
