// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.SearchModuleCollection;

/************************************************************/
/**
 * 
 */
public class IndependentSearchModuleCollection extends SearchModuleCollection {

	/**
	 * 
	 * @return  
	 */
	public String url() {
		return null;
	}
};
