// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;


/************************************************************/
/**
 * Singleton, welches die sprachlichen Ausgaben des Programms verwaltet. Hierbei lässt sich diei Sprache in welcher die Nachrichten ausgegeben werden mittels setLanguage statisch einstellen. Die Nachrichten werden bereits zur Compile-Zeit in den Initialisierungscode des Programms geladen und sind deshalb von Beginn an verfügbar.
 */
public class LanguageManager {
	/**
	 * 
	 */
	private Object messages;
	/**
	 * 
	 */
	private static edu.kit.informatik.studyplan.client.model.system.LanguageManager instance;
	/**
	 * 
	 */
	private static String language;
	/**
	 * 
	 */
	private static String FALLBACK_LANGUAGE = "de";

	/**
	 * 
	 * @return  
	 */
	public static edu.kit.informatik.studyplan.client.model.system.LanguageManager getInstance() {
		return null;
	}

	/**
	 * 
	 * @param langCode 
	 */
	public static void setLanguage(String langCode) {
	}

	/**
	 * 
	 * @param key 
	 * @return  
	 */
	public String getMessage(String key) {
		return null;
	}
};
