// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.Notification;

/************************************************************/
/**
 * 
 */
public class NotificationCollection {
	/**
	 * 
	 */
	private Notification[] notification;
	/**
	 * 
	 */
	private static NotificationCollection instance;

	/**
	 * 
	 * @return  
	 */
	public static NotificationCollection getInstance() {
		return instance;
	}

	/**
	 * 
	 * @param notification 
	 */
	public void add(Notification notification) {
	}
};
