// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.system.Notification;

/************************************************************/
/**
 * Singleton-Collection, welche alle Benachrichtigungen enthält <br>
 * (erweitert Backbone.Collection)
 */
public class NotificationCollection {
    /**
     * Die Collection aller Notifications
     */
    private Collection<Notification> notification;
    /**
     * Die aktuelle Instanz der NotificationCollection
     */
    private static NotificationCollection instance;

    /**
     * Methode zum erhalten der aktuellen Instanz der NotificationCollection
     * 
     * @return Die aktuelle Instanz von NotificationCollection
     */
    public static NotificationCollection getInstance() {
        return instance;
    }

    /**
     * Methode zum hinzufügen einer neuen Benachrichtigung
     * 
     * @param notification
     *            Die Benachrichtigung, welche hinzugefügt werden soll
     */
    public void add(final Notification notification) {
    }
};
