// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

/************************************************************/
/**
 * 
 */
public class Notification {
	/**
	 * 
	 */
	private String title;
	/**
	 * 
	 */
	private String text;
	/**
	 * 
	 */
	private boolean wasShown;
};
