// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.backbone.BackboneModel;

/************************************************************/
/**
 * 
 */
public abstract class OAuthModel extends BackboneModel {
};
