// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.backbone.BackboneCollection;
/************************************************************/
/**
 * 
 */
public abstract class OAuthCollection extends BackboneCollection {
};
