// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.backbone.BackboneModel;

/************************************************************/
/**
 * Diese Klasse repräsentiert ein Model, welches als Resource in der
 * REST-Schnittstelle gespeichert ist, und bei welchem man sich beim Zugriff
 * über OAUTH authentifizieren muss. (Erweitert Backbone.Model)
 */
public abstract class OAuthModel {
    /**
     * Die Synchronisierungs-Methode, welche das Model-Objekt in einem Cookie
     * speichert
     */
    private Object sync;
};
