// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import backbone.BackboneCollection;

/************************************************************/
/**
 * Diese Klasse repräsentiert eine Collection, welche als Resource in der
 * REST-Schnittstelle gespeichert ist, und bei welcher sich man beim Zugriff
 * über OAUTH authentifizieren muss. (Erweitert Backbone.Collection)
 */
public abstract class OAuthCollection {
    /**
     * Die Synchronisierungs-Methode, welche das Model-Objekt in einem Cookie
     * speichert
     */
    private Object sync;
};
