// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.OAuthCollection;
import edu.kit.informatik.studyplan.client.model.system.ObjectiveFunction;

/************************************************************/
/**
 * 
 */
public class ObjectiveFunctionCollection extends OAuthCollection {
	/**
	 * 
	 */
	private ObjectiveFunction[] objectivefunction;
};
