// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.OAuthModel;

/************************************************************/
/**
 * 
 */
public class ObjectiveFunction extends OAuthModel {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private String description;
};
