// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.OAuthModel;

/************************************************************/
/**
 * Klasse, welche eine Objective Function repräsentiert
 */
public class ObjectiveFunction extends OAuthModel {
    /**
     * Name der Objective Function
     */
    private String name;
    /**
     * Beschreibung der Objective Function
     */
    private String description;
};
