// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.SearchModuleCollection;

/************************************************************/
/**
 * 
 */
public class PlanSearchModuleCollection extends SearchModuleCollection {
	/**
	 * 
	 */
	private String postId;

	/**
	 * 
	 * @return  
	 */
	public String url() {
		return postId;
	}
};
