// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.ObjectiveFunction;

/************************************************************/
/**
 * 
 */
public class ProposalInformation {
	/**
	 * 
	 */
	private ObjectiveFunction objectiveFunction;
	/**
	 * 
	 */
	private int maxEctsPerSemester;
	/**
	 * 
	 */
	private String mainDiscipline;
};
