// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.modules.ModuleCollection;

/************************************************************/
/**
 * 
 */
// TODO: Ist das hier + SearchLazyLoadingCollection + SimpleModuleCollection
// noch relevant? (Pagination
// oder keine Pagination - das ist hier die Frage)
public abstract class SearchModuleCollection extends ModuleCollection {
    /**
     * 
     */
    private int minPosModule;

    /**
     * 
     * @param method
     * @param model
     * @param options
     */
    public void sync(final String method, final Object model, final Object options) {
    }
};
