// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.modules.ModuleCollection;

/************************************************************/
/**
 * 
 */
public abstract class SearchModuleCollection extends ModuleCollection {

	/**
	 * 
	 * @param method 
	 * @param model 
	 * @param options 
	 */
	public void sync(String method, Object model, Object options) {
	}
};
