// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

import edu.kit.informatik.studyplan.client.model.system.FilterCollection;
import edu.kit.informatik.studyplan.client.model.system.SearchModuleCollection;
import edu.kit.informatik.studyplan.client.model.system.SimpleModuleCollection;

/************************************************************/
/**
 * 
 */
public class SearchLazyLoadingCollection {
	/**
	 * 
	 */
	private SearchModuleCollection[] searchModules;
	/**
	 * 
	 */
	private FilterCollection filters;
	/**
	 * 
	 */
	private int highestLoaded;

	/**
	 * 
	 * @return  
	 */
	public SimpleModuleCollection getModules() {
		return null;
	}

	/**
	 * 
	 */
	public void loadMoreModules(){
	}

	/**
	 * 
	 * @param filters 
	 */
	public void setFilters(FilterCollection filters) {
	}
};
