// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;

/************************************************************/
/**
 * Singleton, welches die Templates für die Views verwaltet. Jedes Template
 * lässt sich über einen key abrufen.<br>
 * dDie Templates werden zur Compile-Zeit in den Initialisierungscode
 * hineingeladen und sind somit bereits beim Start der Applikation im Template
 * Manager vorhanden. Der Vorteil dieses Vorgehens ist, dass man beim Laden der
 * einzelnen Views nicht auf eine Antwort vom Server (welche das Template
 * enthält) warten muss.
 */
public class TemplateManager {
    /**
     * Das Objekt, welches die templates enthält, auf welche man mittels des
     * Namens zugreifen kann.
     */
    private Object templates;
    /**
     * Die aktuelle Instanz des TemplateManagers
     */
    private static edu.kit.informatik.studyplan.client.model.system.TemplateManager instance;

    /**
     * Methode zum erhalten eines Templates, welches unter dem key gespeichert
     * ist
     * 
     * @param key
     *            Der Key zur identifizierung des Templates
     * @return Gibt eine Funktion zurück, die mit Parametern aufgerufen werden
     *         kann und deren Rückgabewert ein befülltes Template ist
     */
    public Object getTemplate(final String key) {
        return key;
    }

    /**
     * Methode zum erhalten der aktuellen Instanz des TemplateManagers
     * 
     * @return Gibt die aktuelle Instanz des TemplateManagers zurück
     */
    public static edu.kit.informatik.studyplan.client.model.system.TemplateManager getInstance() {
        return null;
    }
};
