// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.system;


/************************************************************/
/**
 * Singleton, welches die Templates für die Views verwaltet. Jedes Template lässt sich über einen key abrufen. Die Templates werden zur Compile-Zeit in den Initialisierungscode hineingeladen und sind somit bereits beim Start der Applikation im Template Manager vorhanden. Der Vorteil dieses Vorgehens ist, dass man beim Laden der einzelnen Views nicht auf eine Antwort vom Server (welche das Template enthält) warten muss.
 */
public class TemplateManager {
	/**
	 * 
	 */
	private Object templates;
	/**
	 * 
	 */
	private static edu.kit.informatik.studyplan.client.model.system.TemplateManager instance;

	/**
	 * 
	 * @param key 
	 * @return  
	 */
	public String getTemplate(String key) {
		return key;
	}

	/**
	 * 
	 * @return  
	 */
	public edu.kit.informatik.studyplan.client.model.system.TemplateManager getInstance() {
		return null;
	}
};
