// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uielement;

import java.lang.reflect.Method;

import edu.kit.informatik.studyplan.client.model.system.SearchCollection;
import edu.kit.informatik.studyplan.client.view.components.filter.ModuleFilter;
import edu.kit.informatik.studyplan.client.view.components.uielement.ModuleList;

/************************************************************/
/**
 * Klasse, welche den Modul Finder repräsentiert. Dieser erlaubt es nach Modulen
 * zu suchen und diese (wenn es sich um eine Sidebar handelt) in einen Plan zu
 * ziehen.
 */
public class ModuleFinder {
    /**
     * Die Collection der Module, welche geladen sind
     */
    private SearchCollection moduleCollection;
    /**
     * Ob es sich bei dem Modul Finder um eine Sidebar handelt. In diesem Fall
     * können Module aus dem ModulFilter in den Plan per Drag and Drop gezogen
     * werden.
     */
    private boolean isSidebar;
    /**
     * Die Filteransicht
     */
    private ModuleFilter moduleFilter;
    /**
     * Die Modulansicht
     */
    private ModuleList moduleList;
    /**
     * Ob Module präferenzierbar sind (dies ist nur möglich, wenn sie im Kontext
     * eines Plans geladen sind)
     */
    private boolean isPreferencable;
    /**
     * Methode, die prüfen kann, ob Module bereits in den Plan gesetzt sind.
     * Diese wird im Konstruktor übergeben.
     */
    private Method isPlaced;

    /**
     * Methode die bei der Suche nach Modulen aufgerufen wird.
     */
    public void onSearch() {
    }

};
