// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uielement;

import edu.kit.informatik.studyplan.client.model.system.Notification;

/************************************************************/
/**
 * Klasse welche eine Benachrichtigungsbox kapselt
 */
public class NotificationBox {
    /**
     * Die anzuzeigende Benachrichtigung
     */
    private Notification notification;

    /**
     * Die Methode, welche die Benachrichtigungsbox schließt
     */
    public void onClose() {
    }

    /**
     * Die Methode, welche nach einem gegebenen Zeitintervall die
     * Benachrichtigung ausblendet
     */
    public void blurOut() {
    }
};
