// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.rest;

/**
 * Die Ressourcenkonfiguration um eine Web-basierte Anwendung zu konfigurieren.
 */
public class ResourceConfig {
};
