// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package org.stuff;


/**
 * Die aus den jOOQ-Bibliotheken importierte Condition-Klasse. Repräsentiert eine SQL-Boolean-Expression.
 */
public class Condition {
};
