// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package org.stuff;

/**
 * Die Ressourcenkonfiguration um eine Web-basierte Anwendung zu konfigurieren.
 */
public class ResourceConfig {
};
