// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/************************************************************/
/**
 * Class modelling a module category.
 * @author NiklasUhl
 * @version 1.0
 */
@Entity
@Table(name = "category")
public class Category {
	
	@Id
	@Column(name = "category_id")
	@JsonProperty("id")
	private int categoryId = -1;
	
	@Column(name = "name")
	@JsonProperty("name")
	private String name;

	@Column(name = "is_subject")
	@JsonIgnore
	private boolean isSubject;

	/**
	 * 
	 * @return gibt die eindeutige Kategorie-ID zurück
	 */
	public int getCategoryId() {
		return categoryId;
	}

	/**
	 * @param categoryId
	 *            the categoryId to set
	 */
	void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * 
	 * @return gibt den Namen der Kategorie zurück
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	void setName(String name) {
		this.name = name;
	}

	/**
	 * 
	 * @return gibt zurück ob es sich bei der Kategorie um ein Vertiefungsfach
	 *         handelt
	 */
	@JsonIgnore
	public boolean isSubject() {
		return isSubject;
	}

	/**
	 * @param isSubject
	 *            the isSubject to set
	 */
	void setSubject(boolean isSubject) {
		this.isSubject = isSubject;
	}
};
