// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/************************************************************/
/**
 * Modelliert eine Modul-Kategorie.
 */
@Entity
@Table(name = "category")
public class Category {
	/**
	 * 
	 */
	@Id
	@Column(name = "category_id")
	private int categoryId;
	/**
	 * 
	 */
	@Column(name = "name")
	private String name;

	@Column(name = "is_subject")
	private boolean isSubject;

	/**
	 * 
	 * @return gibt die eindeutige Kategorie-ID zurück
	 */
	public int getCategoryId() {
		return categoryId;
	}

	/**
	 * 
	 * @return gibt den Namen der Kategorie zurück
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @return gibt zurück ob es sich bei der Kategorie um ein Vertiefungsfach
	 *         handelt
	 */
	public boolean isSubject() {
		return isSubject;
	}
};
