// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * Turnus eines Moduls
 */
public enum CycleType {
	/**
	 * Modul wird nur im Wintersemester angeboten
	 */
	WINTER_TERM,
	/**
	 * Modul wird nur im Sommersemester angeboten
	 */
	SUMMER_TERM,
	/**
	 * Modul wird in jedem Semester angeboten
	 */
	BOTH;
};
