// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import edu.kit.informatik.studyplan.server.rest.StudentResource;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/************************************************************/
/**
 * Class modelling a disciplines
 */
@Entity
@Table(name = "discipline")
public class Discipline {
	/**
	 * 
	 */
	@Id
	@Column(name = "discipline_id")
	@JsonProperty("id")
	@JsonView(StudentResource.Views.StudentClass.class)
	private int disciplineId;
	/**
	 * 
	 */
	@Column(name = "description")
	@JsonProperty("name")  //Yes, name; see REST specs.
	@JsonView(StudentResource.Views.DisciplineClass.class)
	private String description;

	@OneToMany(mappedBy = "discipline")
	private List<Field> fields = new LinkedList<Field>();

	/**
	 * 
	 * @return gibt die eindeutige Studienfach-ID zurück
	 */
	public int getDisciplineId() {
		return disciplineId;
	}

	/**
	 * @param disciplineId
	 *            the disciplineId to set
	 */
	public void setDisciplineId(int disciplineId) {
		this.disciplineId = disciplineId;
	}

	/**
	 * 
	 * @return gibt die Kategoriebeschreibung zurück
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the fields
	 */
	public List<Field> getFields() {
		return fields;
	}
};
