// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/************************************************************/
/**
 * Modelliert ein Studienfach
 */
@Entity
@Table (name = "discipline")
public class Discipline {
	/**
	 * 
	 */
	@Id
	@Column(name = "discipline_id")
	private int disciplineId;
	/**
	 * 
	 */
	@Column(name = "description")
	private String description;

	/**
	 * 
	 * @return gibt die eindeutige Studienfach-ID zurück
	 */
	public int getDisciplineId() {
		return disciplineId;
	}

	/**
	 * 
	 * @return gibt die Kategoriebeschreibung zurück
	 */
	public String getDescription() {
		return description;
	}
};
