// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/************************************************************/
/**
 * Modelliert einen Modultyp, wie beispielsweise Vorlesung, Seminar, etc.
 */
@Entity
@Table(name = "module_type")
public class ModuleType {
	/**
	 * 
	 */
	@Id
	@Column(name = "type_id")
	private int typeId;
	/**
	 * 
	 */
	@Column(name = "name")
	private String name;

	/**
	 * 
	 * @return gibt die eindeutige Typ-ID zurück
	 */
	public int getTypeId() {
		return typeId;
	}

	/**
	 * 
	 * @return gibt den Namen des Typs zurück
	 */
	public String getName() {
		return name;
	}
};
