// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.rest;

import edu.kit.informatik.studyplan.server.filter.FilterDescriptor;
import edu.kit.informatik.studyplan.server.rest.JSONObject;

/************************************************************/
/**
 * 
 */
public class FilterResource {

	/**
	 * 
	 * @return jsonFilter 
	 */
	public JSONObject getAllFilters() {
		return null;
	}
};
