// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.rest;

import edu.kit.informatik.studyplan.server.rest.ResourceConfig;

/************************************************************/
/**
 * 
 */
public class MainApplication extends ResourceConfig {
};
