// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.rest;

import edu.kit.informatik.studyplan.server.rest.JSONObject;

/************************************************************/
/**
 * 
 */
public class PlansResource {

	/**
	 * 
	 * @return jsonPlan 
	 */
	public JSONObject createPlan() {
		return null;
	}

	/**
	 * 
	 * @param jsonPlanList 
	 */
	public void getPlans(JSONObject[] jsonPlanList) {
	}

	/**
	 * 
	 * @param plan_id 
	 * @param jsonPlan 
	 * @return jsonNewPlan 
	 */
	public JSONObject replacePlan(String plan_id, JSONObject jsonPlan) {
		return null;
	}

	/**
	 * 
	 * @param plan_id 
	 * @return jsonPlan 
	 */
	public JSONObject getPlan(String plan_id) {
		return null;
	}

	/**
	 * 
	 * @param plan_id 
	 * @param jsonPlan 
	 * @return jsonChangedPlan 
	 */
	public JSONObject editPlan(String plan_id, JSONObject jsonPlan) {
		return null;
	}

	/**
	 * 
	 * @param plan_id 
	 * @return jsonStatus 
	 */
	public JSONObject deletePlan(String plan_id) {
		return null;
	}

	/**
	 * 
	 * @param plan_id 
	 * @return jsonPlan 
	 */
	public JSONObject duplicatePlan(String plan_id) {
		return null;
	}
};
