// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.rest;

/************************************************************/
/**
 * 
 */
public class ResourceConfig {
};
