// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.generation.objectivefunction.AtomObjectiveFunction;
import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * 
 */
public class MinimalECTSAtomObjectiveFunction extends AtomObjectiveFunction {

	@Override
	public double evaluate(Plan plan) {
		// TODO Auto-generated method stub
		return 0;
	}
};
