// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Minimiert nach der Semesteranzahl. Ein Studienplan mit einem Semester erhält 
 * demzufolge die beste Bewertung.
 */
public class MinimalSemestersAtomObjectiveFunction extends AtomObjectiveFunction {

    /*
     * {@inheritDoc}
     */
	@Override
	public double evaluate(final Plan plan) {
		// TODO Auto-generated method stub
		return 0;
	}
};
