// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.generation.objectivefunction.PartialObjectiveFunction;

/************************************************************/
/**
 * 
 */
public abstract class ObjectiveFunction implements PartialObjectiveFunction {
	/**
	 * 
	 */
	private PartialObjectiveFunction[] partialobjectivefunction;
};
