// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

/************************************************************/
/**
 * Eine Zielfunktion dient zur be
 */
public abstract class ObjectiveFunction implements PartialObjectiveFunction {
	/**
	 * 
	 */
	private PartialObjectiveFunction[] partialobjectivefunction;
};
