// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * 
 */
public interface PartialObjectiveFunction {

	/**
	 * 
	 * @return  
	 * @param plan 
	 */
	public double evaluate(Plan plan);
};
