// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.filter;

import edu.kit.informatik.studyplan.client.model.system.Filter;

/************************************************************/
/**
 * Klasse, welche die Anzeige eine eines Filters kapselt.
 */
public abstract class FilterComponent {
    /**
     * Die ID des Filters
     */
    private String id;
    /**
     * Der Filter, welcher visualisiert wird
     */
    private Filter filter;

    /**
     * Methode zum erhalten der ID des Filters
     * 
     * @return Die ID des Filters
     */
    public String getId() {
        return id;
    }

    /**
     * Methode zum erhalten des Filter-Modells
     * 
     * @return
     */
    public Filter getFilter() {
        return filter;

    }

    /**
     * Methode welche bei der Auswahl eines Filterobjekts ausgeführt wird
     */
    public abstract void onSelect();
};
