// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.filter;

import edu.kit.informatik.studyplan.client.view.components.filter.FilterComponent;

/************************************************************/
/**
 * Filter, welcher durch die Eingabe eines Suchtexts aktiviert wird
 */
public class TextFilter extends FilterComponent {

    /**
     * Methode welche bei der Auswahl eines Filterobjekts ausgeführt wird
     */
    public void onSelect() {
    }
};
