// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.backbone;

/************************************************************/
/**
 * 
 */
public class BackboneModel {
};
