// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.userdata.PreferenceType;

/************************************************************/
/**
 * 
 */
public class ModulePreference {
	/**
	 * 
	 */
	private Module module;
	/**
	 * 
	 */
	private PreferenceType type;

	/**
	 * 
	 * @return  
	 */
	public Module getModule() {
		return module;
	}

	/**
	 * 
	 * @param module 
	 */
	public void setModule(Module module) {
	}

	/**
	 * 
	 * @return  
	 */
	public PreferenceType getPreference() {
		return type;
	}

	/**
	 * 
	 * @param preferenceType 
	 */
	public void setPreference(PreferenceType preferenceType) {
	}
};
