// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;

/************************************************************/
/**
 * 
 */
public class ModuleEntry {
	/**
	 * 
	 */
	private Module module;
	/**
	 * 
	 */
	private int semester;

	/**
	 * 
	 * @return  
	 */
	public Module getModule() {
		return module;
	}

	/**
	 * 
	 * @param module 
	 */
	public void setModule(Module module) {
	}

	/**
	 * 
	 * @return  
	 */
	public int getSemester() {
		return semester;
	}

	/**
	 * 
	 * @param semester 
	 */
	public void setSemester(int semester) {
	}
};
