// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

/************************************************************/
/**
 * 
 */
public enum PreferenceType {
	/**
	 * 
	 */
	POSITIVE,
	/**
	 * 
	 */
	NEGATIVE;
};
