// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

/************************************************************/
/**
 * 
 */
public enum SemesterType {
	/**
	 * 
	 */
	WINTER_TERM,
	/**
	 * 
	 */
	SUMMER_TERM;
};
