// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

/************************************************************/
/**
 * 
 */
public enum VerificationState {
	/**
	 * 
	 */
	NOT_VERIFIED,
	/**
	 * 
	 */
	VALID,
	/**
	 * 
	 */
	INVALID;
};
