// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

import java.util.List;

import edu.kit.informatik.studyplan.server.filter.Filter;
import edu.kit.informatik.studyplan.server.model.moduledata.Category;
import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDao;

/************************************************************/
/**
 * Ein konkretes ModulDao, welches die Datenbankverbindung über Hibernate
 * herstellt. Es kann nur auf Module, Kategorien und Vertiefungsfächer des im
 * Konstruktur angebenen Studiengangs zugreifen
 */
class HibernateModuleDao implements ModuleDao {

	/**
	 * initialisiert ein neues DAO
	 */
	public HibernateModuleDao() {

	}

	public Module getModuleById(String id) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Module> getModulesByFilter(Filter filter, Discipline discipline) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Module> getModulesByFilter(Filter filter, Discipline discipline, int start, int end) {
		// TODO Auto-generated method stub
		return null;
	}

	public Module getRandomModuleByFilter(Filter filter, Discipline discipline) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Discipline> getDisciplines() {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Category> getCategories(Discipline discipline) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Category> getFields(Discipline discipline) {
		// TODO Auto-generated method stub
		return null;
	}

};
