// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

/**
 * Kapselt die für die Filterarchitektur nötigen Module-Attribut-Namen als
 * Stringkonstanten. Diese werden bei der Anwendung der Filter in den
 * ModuleDao-Methoden für die eindeutige Identifzierung von Module-Eigenschaften
 * benutzt.
 * 
 * @see edu.kit.informatik.studyplan.server.filter
 * @see ModuleDao
 */
public final class ModuleAttributeNames {
	/**
	 * Stringkonstante, die die ECTS-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String CREDIT_POINTS = "creditPoints";
	/**
	 * Stringkonstante, die die Kategorie-Eigenschaft eines Moduls
	 * repräsentiert.
	 */
	public static final String CATEGORY = "category";
	/**
	 * Stringkonstante, die die Modultyp-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String MODULE_TYPE = "moduleType";
	/**
	 * Stringkonstante, die die Turnus-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String CYCLE_TYPE = "cycleType";
	/**
	 * Stringkonstante, die die Fachrichtungs-Eigenschaft eines Moduls
	 * repräsentiert.
	 */
	public static final String DISCIPLINE = "discipline";
	/**
	 * Stringkonstante, die die Wahl-/Pflicht-Veranstaltungs-Eigenschaft eines
	 * Moduls repräsentiert.
	 */
	public static final String IS_COMPULSORY = "compulsory";
	/**
	 * Stringkonstante, die die Modulnamens-Eigenschaft eines Moduls
	 * repräsentiert.
	 */
	public static final String NAME = "name";
};
