// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDao;

/************************************************************/
/**
 * Factory zur ModuleDao-Erzeugung
 */
public class ModuleDaoFactory {

	/**
	 * 
	 * @return liefert das für die verwendete Datenbankschnittstelle benötigte
	 *         DAO zurück.
	 */
	public static ModuleDao getModuleDao() {
		return null;
	}
};
