// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.user;

import edu.kit.informatik.studyplan.client.model.system.OAuthModel;
import edu.kit.informatik.studyplan.client.model.user.PassedModuleCollection;

/************************************************************/
/**
 * Klasse, welche den Studenten beschreibt
 */
public class Student extends OAuthModel {
    /**
     * Die Collection der bestandenen Module des Studenten
     */
    private PassedModuleCollection passedModules;
    /**
     * Die ID des Nutzers
     */
    private String userId;
    /**
     * Der Nutzername
     */
    private String username;
    /**
     * Das Fach des Nutzers
     */
    private String discipline;
    /**
     * Ob der Student im Sommer- (SS) oder Wintersemester (WS) angefangen hat zu
     * studieren
     */
    private String studystartCycle;
    /**
     * Das Jahr in dem der Student angefangen hat zu studieren
     */
    private int studyStartYear;
};
