// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

import edu.kit.informatik.studyplan.client.view.components.uielement.Plan;

/************************************************************/
/**
 * Anzeige, welche 2 Pläne vergleicht
 */
public class ComparisonView {
    /**
     * Der linke Plan des Vergleichs
     */
    private Plan plan1;
    /**
     * Der rechte Plan des Vergleichs
     */
    private Plan plan2;
};
