// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

import edu.kit.informatik.studyplan.client.model.system.ProposalInformation;
import edu.kit.informatik.studyplan.client.view.components.uielement.Plan;
import edu.kit.informatik.studyplan.client.view.components.uipanel.WizardComponent;

/************************************************************/
/**
 * Klasse, welche die erste Seite des Generierungs-Wizards kapselt.
 */
public class GenerationWizardComponent1 extends WizardComponent {
    /**
     * Plan für welchen generiert werden soll
     */
    private Plan plan;
    /**
     * Die notwendigen Informationen für die Generierung
     */
    private ProposalInformation information;

    /**
     * Gibt Objekt vom Typ GenerationWizardComponent2 zurück
     * 
     * @return Objekt vom Typ GenerationWizardComponent2 (zweite Seite des
     *         Wizards)
     */
    public WizardComponent next() {
        return null;
    }

    /**
     * Methode, welche bei Veränderungen des Seiteninhalts aufgerufen wird.
     */
    public void onChange() {
    }
};
