// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.plans.PlanCollection;
import edu.kit.informatik.studyplan.client.view.components.uielement.PlanListElement;

/************************************************************/
/**
 * Klasse, welche eine Liste von Plänen kapselt
 */
public class PlanList {
    /**
     * Die Pläne, welche angezeigt werden sollen
     */
    private PlanCollection planCollection;
    /**
     * Die Elemente, welche in der Liste angezeigt werden
     */
    private Collection<PlanListElement> planListElements;

    /**
     * Listener, der aufgerufen wird, wenn eine Aktion für einen/mehrere Pläne
     * aufgerufen wird.
     */
    public void onActionSelection() {
    }

    /**
     * Methode, welche bei einer Veränderung der Pläne aufgerufen wird
     */
    public void onChange() {
    }
};
