// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

/************************************************************/
/**
 * Klasse, welche eine Komponente eines Wizards kapselt. Die Wizards sind nach
 * dem Konzept des State-Machine-Patterns aufgebaut
 */
public abstract class WizardComponent {

    /**
     * Methode, welche den View-Component der nächsten Seite des Wizard zurück
     * gibt
     * 
     * @return Den View-Component der nächsten Siete des Wizard
     */
    public abstract edu.kit.informatik.studyplan.client.view.components.uipanel.WizardComponent next();
};
