// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.plans.Plan;
import edu.kit.informatik.studyplan.client.model.system.OAuthCollection;

/************************************************************/
/**
 * 
 */
public class PlanCollection extends OAuthCollection {
	/**
	 * 
	 */
	private Plan[] plan;
};
