// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.plans.SemesterCollection;
import edu.kit.informatik.studyplan.client.model.system.OAuthModel;

/************************************************************/
/**
 * 
 */
public class Plan extends OAuthModel {
	/**
	 * 
	 */
	private SemesterCollection semestercollection;
	/**
	 * 
	 */
	private int planId;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private int creditPoints;
	/**
	 * 
	 */
	private String verificationState;

	/**
	 * 
	 * @param moduleId 
	 */
	public void containsModule(int moduleId) {
	}

	/**
	 * 
	 */
	public void loadVerification() {
	}
};
