// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.plans.Plan;

/************************************************************/
/**
 * 
 */
public class PropesedPlan extends Plan {

	/**
	 * 
	 * @param options 
	 */
	public void save(Object options) {
	}
};
