// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.modules.ModuleCollection;

/************************************************************/
/**
 * 
 */
public class Semester extends ModuleCollection {
	/**
	 * 
	 */
	private String planId;

	@Override
	public String url() {
		// TODO Auto-generated method stub
		return null;
	}
};
