// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.plans.Semester;

/************************************************************/
/**
 * 
 */
public class SemesterCollection {
	/**
	 * 
	 */
	private Semester[] semester;
};
