// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.plans.Semester;

import backbone.BackboneModel;

/************************************************************/
/**
 * Eine Collection von Semestern, welche von einem Plan genutzt wird. (Erbt von
 * Backbone.Collection)
 */
public class SemesterCollection {
    /**
     * Die in der Collection enthaltenen Semester
     */
    private Collection<Semester> semester;
};
