// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.router;

/************************************************************/
/**
 * 
 */
public class MainRouter {

	/**
	 * 
	 */
	public void mainPage() {
	}

	/**
	 * 
	 * @param planId 
	 */
	public void editPage(String planId) {
	}

	/**
	 * 
	 * @param plan1Id 
	 * @param plans2Id 
	 */
	public void comparisonPage(String plan1Id, String plans2Id) {
	}

	/**
	 * 
	 */
	public void loginPage() {
	}

	/**
	 * 
	 */
	public void showProfile() {
	}

	/**
	 * 
	 */
	public void signUpWizard() {
	}

	/**
	 * 
	 */
	public void generationWizard() {
	}

	/**
	 * 
	 */
	public void handleLogin() {
	}
};
