// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.router;

/************************************************************/
/**
 * Klasse, welche das Routing zu den verschiedenen Seiten hin übernimmt. Die
 * Methoden stoßen dann jeweils die entsprechenden Änderungen im View an.
 */
public class MainRouter {

    /**
     * Methode zur Anzeige der Hauptseite<br>
     * <i>/</i>
     */
    public void mainPage() {
    }

    /**
     * Methode zum anzeigen der Plan-Bearbeiten-Seite<br>
     * <i>/plan/{planId}</i>
     * 
     * @param planId
     *            Die ID des Plans
     */
    public void editPage(final String planId) {
    }

    /**
     * Methode zum anzeigen der Pläne-Vergleichen-Seite<br>
     * <i>/compare/{plan1Id}/{plan2Id}</i>
     * 
     * @param plan1Id
     *            Die ID des ersten Plans
     * @param plans2Id
     *            Die ID des zweiten Plans
     */
    public void comparisonPage(final String plan1Id, final String plans2Id) {
    }

    /**
     * Methode zum anzeigen der Login-Seite<br>
     * <i>/login</i>
     */
    public void loginPage() {
    }

    /**
     * Methode zum anzeigen des Profils<br>
     * <i>/profile</i>
     */
    public void showProfile() {
    }

    /**
     * Methode zum anzeigen des Registrierungs-Wizards<br>
     * <i>/signup</i>
     */
    public void signUpWizard() {
    }

    /**
     * Methode zum anzeigen des Generierungs-Wizards<br>
     * <i>/plan/{planId}/generate</i>
     */
    public void generationWizard(final int planId) {
    }

    /**
     * Methode zum verarbeiten der OAuth Antwort vom Server. Diese Methode
     * leitet dann an die entsprechende Seite (Hauptseite oder Login) weiter.
     * <br>
     * <i>/processLogin</i>
     */
    public void handleLogin() {
    }
};
