// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification.standard;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;
import edu.kit.informatik.studyplan.server.verification.VerificationResult;
import edu.kit.informatik.studyplan.server.verification.Verifier;

/************************************************************/
/**
 * 
 */
public class StandardVerifier {

	/**
	 * 
	 * @return invalid 
	 * @param plan 
	 */
	public VerificationResult verify(Plan plan) {
		return null;
	}
};
