// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

/************************************************************/
/**
 * Die Klasse NodeWithoutOutput erbt von Node und stellt Blätter der
 * Graphenstruktur da, das heißt Module, die nicht Voraussetzung für ein anderes
 * Modul des Studienplans sind.
 */
public class NodeWithoutOutput extends Node {
};
