// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

/************************************************************/
/**
 * Die Klasse Weightfunction enthält eine Methode, welche die Anzahl an
 * Creditpoints eines Knotens und aller seiner innerer Knoten bestimmt.
 */
public class WeightFunction {
	/**
	 * Die Methode getWeight errechnet die Punktanzahl eines Knoten (Node) und
	 * aller innerer Knoten dieses Knotens, addiert sie und gibt diese int-Zahl
	 * zurück.
	 * 
	 * @param node
	 *            der Knoten, dessen Creditpoint-Anzahl bestimmt werden soll.
	 * @return die Gesamtanzahl an Creditpoints des Knotens.
	 */
	public int getWeight(Node node) {
		return 0;
	}
};
