// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDao;

/************************************************************/
/**
 * Factory zur ModuleDao-Erzeugung
 */
public class ModuleDaoFactory {

	/**
	 * 
	 * @return liefert das für die verwendete Datenbankschnittstelle benötigte DAO zurück <br>
	 * Das DAO wird mit dem übergebenen Studiengang initialisiert.
	 * @param discipline der Studiengang
	 */
	public static ModuleDao getModuleDao(Discipline discipline) {
		return null;
	}
};
