// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.plans;

import edu.kit.informatik.studyplan.client.model.modules.ModuleCollection;

/************************************************************/
/**
 * Klasse, welcher ein Semester als Collection von Modulen beschreibt.
 */
public class Semester extends ModuleCollection {
    /**
     * Die ID des Plans zu welchem das Semester gehört.
     */
    private String planId;

    @Override
    public String url() {
        // TODO Auto-generated method stub
        return null;
    }
};
