// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uielement;

import java.util.Collection;

import edu.kit.informatik.studyplan.client.model.system.SearchCollection;

/************************************************************/
/**
 * 
 */
public class ModuleList {
    /**
     * Die Liste der Module, welche angezeigt werden sollen
     */
    private SearchCollection modules;
    /**
     * Die Modulboxen in welchen die Module angezeigt werden.
     */
    private Collection<ModuleBox> moduleBox;
    /**
     * Ob die Module in den Boxen präferenzierbar sind (nur im Zusammenhang mit
     * einem Plan)
     */
    private boolean isPreferencable;
};
