// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uielement;

import edu.kit.informatik.studyplan.client.model.plans.Plan;

/************************************************************/
/**
 * Klasse, welche die Kopfzeile des Plans kapselt
 */
public abstract class PlanHeadBar {
    /**
     * Der Plan, welcher angezeigt wird.
     */
    private Plan plan;

    /**
     * Die Methode, welche bei einer Änderung des Plans aufgerufen wird.
     */
    public void onChange() {
    }
};
