// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.pluginmanager;

import edu.kit.informatik.studyplan.server.generation.Generator;
import edu.kit.informatik.studyplan.server.generation.objectivefunction.PartialObjectiveFunction;

/************************************************************/
/**
 * 
 */
public class GenerationManager {
	/**
	 * 
	 */
	private Generator generator;
	/**
	 * 
	 */
	private PartialObjectiveFunction[] objectiveFunction;
};
