// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.pluginmanager;

import edu.kit.informatik.studyplan.server.verification.Verifier;

/************************************************************/
/**
 * 
 */
public class VerificationManager {
	/**
	 * 
	 */
	public Verifier verifier;
};
