// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.Filter;
import edu.kit.informatik.studyplan.server.filter.FilterDescriptor;
import edu.kit.informatik.studyplan.server.filter.FilterType;
import org.jooq.Field;

import static org.jooq.impl.DSL.field;

/**
 * Repräsentiert einen Filter für ein bestimmtes Module-Attribut.
 */
public abstract class AttributeFilter implements Filter {

	/**
	 * Liefert den Namen des Module-Attributs, das durch beschriebenen Filter
	 * gefiltert werden soll.
	 *
	 * @return der Attribut-Name
	 */
	public abstract String getAttributeName();

	/**
	 * Gibt ein jOOQ-Field-Objekt zurück, das des Filters attributeName kapselt.
	 *
	 * @return das jOOQ-Field-Objekt
	 */
	protected Field<Object> toField() {
		return field(getAttributeName());
	}


	/**
	 * Liefert den Filter-Typ des AttributeFilters.
	 * 
	 * @return der Filter-Typ
	 */
	public abstract FilterType getFilterType();
};
