// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

/**
 * Die aus den jOOQ-Bibliotheken importierte Condition-Klasse. Repräsentiert
 * eine SQL-Boolean-Expression.
 */
public class Condition {
};
