// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleAttributeNames;

/**
 * Repräsentiert einen ECTS-Intervall-Filter.
 */
public final class CreditPointsFilter extends RangeFilter {
	/**
	 * Erzeugt einen neuen ECTS-Intervall-Filter mit gegebenen Schranken.
	 *
	 * @param lower
	 *            untere Schranke des Filters
	 * @param upper
	 *            obere Schranke des Filters
	 * @param min
	 *            minimale untere Schranke des Filters
	 * @param max
	 *            maximale obere Schranke des Filters
	 */
	public CreditPointsFilter(int lower, int upper, int min, int max) {
		super(lower, upper, min, max);
	}

	@Override
	public String getAttributeName() {
		return ModuleAttributeNames.CREDIT_POINTS;
	}
};
