// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleAttributeNames;

/**
 * Represents a credit points interval filter.
 */
public final class CreditPointsFilter extends RangeFilter {
	/**
	 * Creates a new CreditPointsFilter with given ranges.
	 *
	 * @param lower
	 *            lower bound of the filter.
	 * @param upper
	 *            upper bound of the filter
	 * @param min
	 *            minimum lower bound of the filter.
	 * @param max
	 *            maximum upper bound of the filter
	 */
	public CreditPointsFilter(int lower, int upper, int min, int max) {
		super(lower, upper, min, max);
	}

	@Override
	public String getAttributeName() {
		return ModuleAttributeNames.CREDIT_POINTS;
	}
};
