// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

/**
 * Repräsentiert einen Filter für Module über eine Filterbedingung.
 */
public interface Filter {

	/**
	 * Gibt die Filterbedingung als jOOQ-Condition-Objekt zurück.
	 * 
	 * @return die Filterbedingung
	 */
	public org.jooq.Condition getCondition();
};
