// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import java.util.HashMap;
import java.util.Map;

/**
 * Beschreibungen der nach außen sichtbaren Filterklassen für den Client.
 * Descriptions of the published filter classes for the client.
 */
public class FilterDescriptor {
	FilterDescriptor(int id, AttributeFilter defaultFilter, String filterName, String tooltip) {
		this.id = id;
		this.filterName = filterName;
		this.tooltip = tooltip;
		this.defaultFilter = defaultFilter;
	}

	private int id;

	private String filterName;

	private String tooltip;

	private AttributeFilter defaultFilter;

	/**
	 * 
	 * @return a JSON representation of the described filter for the client.
	 */
	public Map<String, Object> toJson() {
		Map<String, Object> result = new HashMap<>(5);
		result.put("id", getId());
		result.put("name", getFilterName());
		result.put("default-value", getDefaultFilter().getFilterType().defaultJsonValue(getDefaultFilter()));
		result.put("tooltip", getTooltip());
		result.put("specification", getDefaultFilter().getFilterType().toJsonSpecification(getDefaultFilter()));
		return result;
	};

	/**
	 * 
	 * @return the filter id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return a default object of the described filter type.
	 */
	public AttributeFilter getDefaultFilter() {
		return defaultFilter;
	}

	/**
	 * 
	 * @return the filter name (used for GUI purposes)
	 */
	public String getFilterName() {
		return filterName;
	}

	/**
	 * 
	 * @return a tooltip for the filter (for GUI purposes).
	 */
	public String getTooltip() {
		return tooltip;
	}
};
