// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.condition.Condition;

import java.util.List;

/**
 * Repräsentiert einen Filter für Module über eine Filterbedingung.
 */
public interface Filter {

	/**
	 * Returns the filter condition as a list of {@link Condition} objects.
	 * 
	 * @return the filter condition.
	 */
	public List<Condition> getConditions();
};
