// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.filter;

import edu.kit.informatik.studyplan.client.view.components.filter.FilterComponent;

import java.util.Collection;

/************************************************************/
/**
 * Filter, welcher durch die Auswahl eines Elements aktiviert wird
 */
public class SelectFilter extends FilterComponent {
    /**
     * Die vorhandenen Optionen des Filters
     */
    private Collection<String> options;

    /**
     * Methode welche bei der Auswahl eines Filterobjekts ausgeführt wird
     */
    public void onSelect() {
    }
};
