// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.modules;

/************************************************************/
/**
 * 
 */
public class ModuleConstraint {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private int modul1Id;
	/**
	 * 
	 */
	private int modul2Id;
	/**
	 * 
	 */
	private String type;
	/**
	 * 
	 */
	private String descriptionModule1;
	/**
	 * 
	 */
	private String descriptionModule2;
};
