// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.modules;

import edu.kit.informatik.studyplan.client.model.system.OAuthCollection;

/************************************************************/
/**
 * 
 */
public abstract class ModuleCollection extends OAuthCollection {

	/**
	 * 
	 * @return  
	 */
	public abstract String url();
};
