// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.modules;

import edu.kit.informatik.studyplan.client.model.modules.ModuleConstraint;
import edu.kit.informatik.studyplan.client.model.modules.Preference;

/************************************************************/
/**
 * 
 */
public class Module {
	/**
	 * 
	 */
	private Preference preference;
	/**
	 * 
	 */
	private String moduleId;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private int creditPoints;
	/**
	 * 
	 */
	private String cycleType;
	/**
	 * 
	 */
	private boolean compulsory;
	/**
	 * 
	 */
	private String description;
	/**
	 * 
	 */
	private String lecturer;
	/**
	 * 
	 */
	private String category;
	/**
	 * 
	 */
	private String discipline;
	/**
	 * 
	 */
	private String postId;
	/**
	 * 
	 */
	private ModuleConstraint moduleconstraint;
	/**
	 * 
	 */
	private boolean passed;
};
