// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.modules;

/************************************************************/
/**
 * Diese Klasse beschreibt einen zu einem Modul gehörenden System-Constraint
 */
public class ModuleConstraint {
    /**
     * Der Typ des ModuleConstraint. Dieser wird als String angegeben.
     */
    private String name;
    /**
     * Die ID des ersten Moduls
     */
    private int modul1Id;
    /**
     * Die ID des zweiten Moduls
     */
    private int modul2Id;
    /**
     * Textuelle Beschreibung des ModuleConstraints für den Nutzer
     */
    private String type;
};
