// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.modules;

/************************************************************/
/**
 * 
 */
public class Preference {
	/**
	 * 
	 */
	private int value;
	/**
	 * 
	 */
	private int moduleId;
	/**
	 * 
	 */
	private String postId;

	/**
	 * 
	 * @return  
	 */
	public String url() {
		return postId;
	}
};
