// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

import edu.kit.informatik.studyplan.server.generation.Generator;
import edu.kit.informatik.studyplan.server.generation.objectivefunction.PartialObjectiveFunction;
import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDao;
import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 *Die Klasse SimpleGenerator, welche Generator implementiert,
 * stellt einen konkreten Generator da. Dieser nutzt die Graphenstruktur, 
 * die Zielfunktion und die WeightFunction.
 */
public class SimpleGenerator implements Generator {

	@Override
	public Plan generate(PartialObjectiveFunction objectiveFunction, Plan currentPlan, ModuleDao moduleDAO) {
		// TODO Auto-generated method stub
		return null;
	}
};
