// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.authorization;

/************************************************************/
/**
 * Berechtigungen die ein Nutzer anfragen kann
 */
public enum AuthorizationScope {
	/**
	 * Berechtigung Student. Kann alle Kernfunktionen nutzen.
	 */
	STUDENT;
};
