// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.authorization;

import java.net.URL;
import java.util.Collection;
import java.util.List;

import edu.kit.informatik.studyplan.server.model.userdata.authorization.AuthorizationScope;

/************************************************************/
/**
 * Modelliert einen Klienten, der auf die REST-Schnittstelle zugreifen kann
 * siehe Kapitel ????
 */
public class RESTClient {
	/**
	 * 
	 */
	private String apiKey;
	/**
	 * 
	 */
	private String apiSecret;
	/**
	 * 
	 */
	private String origin;
	/**
	 * 
	 */
	private String redirectUrl;
	/**
	 * 
	 */
	private Collection<AuthorizationScope> scopes;

	/**
	 * 
	 * @return gibt die eindeutige ID des Klienten zurück
	 */
	public String getApiKey() {
		return apiKey;
	}

	/**
	 * 
	 * @param apiKey die ID des Klienten
	 */
	public void setApiKey(String apiKey) {
	}

	/**
	 * 
	 * @return gibt die nur dem Klienten bekannte Kennung zurück
	 */
	public String getApiSecret() {
		return apiKey;
	}

	/**
	 * 
	 * @param apiSecret die Kennung
	 */
	public void setApiSecret(String apiSecret) {
	}

	/**
	 * 
	 * @return gibt die Domain, von welcher aus der Client auf Ressourcen zugreifen kann als regulären Ausdruck zurück.
	 */
	public String getOrigin() {
		return apiKey;
	}

	/**
	 * 
	 * @param der reguläre Ausdruck
	 */
	public void setOrigin(String origin) {
	}

	/**
	 * 
	 * @return gibt die Weiterleitungs-URL zurück
	 */
	public URL getRedirectUrl() {
		return null;
	}

	/**
	 * 
	 * @param redirectUrl die Weiterleitungs-URL
	 */
	public void setRedirectUrl(URL redirectUrl) {
	}

	/**
	 * 
	 * @return gibt eine Liste aller Berechtigungen zurück, die vom Client angefragt werden können
	 */
	public List<AuthorizationScope> getScopes() {
		return null;
	}
};
