// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.authorization;

import java.time.LocalDateTime;

import org.hibernate.Session;

import edu.kit.informatik.studyplan.server.model.HibernateUtil;
import edu.kit.informatik.studyplan.server.model.userdata.User;

/************************************************************/
/**
 * Konkrete Implementierung eines Security-Providers, der Hibernate verwendet.
 */
class SecurityProvider extends AbstractSecurityProvider {
	
	private Session session;
	
	SecurityProvider() {
		this.session = HibernateUtil.getUserDataSessionFactory().openSession();
	}
	
	@Override
	public AuthorizationContext generateAuthorizationContext(User user, RESTClient client) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public AuthorizationContext getAuthorizationContext(String accessToken) {
		session.beginTransaction();
		AuthorizationContext authorizationContext = session.byId(AuthorizationContext.class).load(accessToken);
		session.getTransaction().commit();
		if (authorizationContext != null) {
			if (authorizationContext.getExpiryDate().isBefore(LocalDateTime.now())) {
				authorizationContext = null;
			}
			authorizationContext.setProvider(this);
		}
		return authorizationContext;
	}

	@Override
	public RESTClient getClient(String clientId) {
		session.beginTransaction();
		RESTClient client = session.byId(RESTClient.class).load(clientId);
		session.getTransaction().commit();
		return client;
	}

	@Override
	public void cleanUp() {
		session.close();
	}
};
