// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model;

import org.hibernate.SessionFactory;

/************************************************************/
/**
 * Fabrik zur Erzeugung von SessionFactories. Diese sind das
 * Hibernate-Äquivalent zu Datenbankverbindungen.
 */
class HibernateUtil {

	/**
	 * Erzeugt die SessionFactory zum Zugriff auf die Modul-Datenbank aus der
	 * entsprechenden Konfigurationsdatei
	 * 
	 * @return die SessionFactory
	 */
	static SessionFactory getModuleDataSessionFactory() {
		return null;
	}

	/**
	 * Erzeugt die SessionFactory zum Zugriff auf die Nutzer-Datenbank aus der
	 * entsprechenden Konfigurationsdatei
	 * 
	 * @return die SessionFactory
	 */
	static SessionFactory getUserDataSessionFactory() {
		return null;
	}
};
