// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model;

import org.hibernate.SessionFactory;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;

/************************************************************/
/**
 * Fabrik zur Erzeugung von SessionFactories. Diese sind das
 * Hibernate-Äquivalent zu Datenbankverbindungen.
 */
public final class HibernateUtil {

	private static SessionFactory moduleDataSessionFactory;

	private static SessionFactory userDataSessionFactory;

	private HibernateUtil() {
	}

	/**
	 * Erzeugt die SessionFactory zum Zugriff auf die Modul-Datenbank aus der
	 * entsprechenden Konfigurationsdatei
	 * 
	 * @return die SessionFactory
	 */
	public static SessionFactory getModuleDataSessionFactory() {
		if (moduleDataSessionFactory == null) {
			StandardServiceRegistry standardRegistry = new StandardServiceRegistryBuilder()
					.configure("moduledata.cfg.xml").build();
			Metadata metadata = new MetadataSources(standardRegistry).buildMetadata();
			moduleDataSessionFactory = metadata.buildSessionFactory();
		}

		return moduleDataSessionFactory;
	}

	/**
	 * Erzeugt die SessionFactory zum Zugriff auf die Nutzer-Datenbank aus der
	 * entsprechenden Konfigurationsdatei
	 * 
	 * @return die SessionFactory
	 */
	public static SessionFactory getUserDataSessionFactory() {
		if (userDataSessionFactory == null) {
			StandardServiceRegistry standardRegistry = new StandardServiceRegistryBuilder()
					.configure("userdata.cfg.xml").build();
			Metadata metadata = new MetadataSources(standardRegistry).buildMetadata();
			userDataSessionFactory = metadata.buildSessionFactory();
		}

		return userDataSessionFactory;
	}

};
