// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import edu.kit.informatik.studyplan.server.model.userdata.dao.UserDao;

/************************************************************/
/**
 * Factory zur UserDao-Erzeugung
 */
public class UserDaoFactory {

	/**
	 * 
	 * @return liefert das für die verwendete Datenbankschnittstelle benötigte DAO zurück
	 */
	public static UserDao getUserDao() {
		return null;
	}
};
