// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification;

import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraint;

/************************************************************/
/**
 * 
 */
public class VerificationResult {
	/**
	 * 
	 */
	private ModuleConstraint[] violations;

	/**
	 * 
	 * @return  
	 */
	public boolean isCorrect() {
		return false;
	}
};
