// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;
import edu.kit.informatik.studyplan.server.verification.VerificationResult;

/************************************************************/
/**
 * 
 */
public interface Verifier {

	/**
	 * 
	 * @return invalid 
	 * @param plan 
	 */
	public VerificationResult verify(Plan plan);
};
