// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * The AtomObjectiveFunction is a partial objective function, that considers only one 
 * characteristic.
 */
public abstract class AtomObjectiveFunction implements PartialObjectiveFunction {

	/*
	 * {@inheritDoc}
	 */
	public abstract double evaluate(Plan plan);
};
