// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import java.util.Collections;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Minimiert nach der Semesteranzahl. Ein Studienplan mit einem Semester erhält
 * demzufolge die beste Bewertung.
 */
public class MinimalSemestersAtomObjectiveFunction extends AtomObjectiveFunction {

	private static double quotient = 0.965;
	
	public MinimalSemestersAtomObjectiveFunction() {
		setDescriptor("minimale Semesterzahl");
	}
	
	/*
	 * {@inheritDoc}
	 */
	@Override
	public double evaluate(final Plan plan) {
		int maxSemester = Collections.max(plan.getAllModuleEntries()).getSemester();
		if (maxSemester < 1) {
			maxSemester = 1;
		}
		return Math.pow(quotient, maxSemester - 1);
	}
};
