// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Je geringer die Gesamtanzahl der ECTS in einem Studienplan, desto besser ist
 * die Bewertung von MinimalECTSAtomObjectiveFunction. Zu beachten ist jedoch,
 * dass sobald ein gewisser Schwellwert unterschritten wird alle Studienpläne
 * die Bestnote erhalten.
 */
public class MinimalECTSAtomObjectiveFunction extends AtomObjectiveFunction {
	
	private static double quotient = 1.0 / 1.03;
	
	public MinimalECTSAtomObjectiveFunction() {
		setDescriptor("minimale ECTS-Zahl");
	}
	/*
	 * {@inheritDoc}
	 */
	@Override
	public double evaluate(final Plan plan) {
		int threshold = (int) plan.getUser().getDiscipline().getFields()
				.stream().mapToDouble(field -> field.getMinEcts()).sum();
		int exponent = (int) plan.getCreditPoints() - threshold;
		if (exponent < 0) {
			exponent = 0;
		}
		return Math.pow(quotient, exponent);
	}
};
