// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Optimiert nach den Nutzerbewertungen. Ideal ist, wenn alle Nutzerbewertungen
 * berücksichtigt wurden, also alle positiv bewerteten Module im Studienplan zu
 * finden sind und kein negativ bewertetes.
 */
public class ModulePreferencesAtomObjectiveFunction extends AtomObjectiveFunction {

	/*
	 * {@inheritDoc}
	 */
	@Override
	public double evaluate(final Plan plan) {
		// TODO Auto-generated method stub
		return 0;
	}
};
