// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.userdata.ModulePreference;
import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Optimiert nach den Nutzerbewertungen. Ideal ist, wenn alle Nutzerbewertungen
 * berücksichtigt wurden, also alle positiv bewerteten Module im Studienplan zu
 * finden sind und kein negativ bewertetes.
 */
public class ModulePreferencesAtomObjectiveFunction extends AtomObjectiveFunction {

	/*
	 * {@inheritDoc}
	 */
	@Override
	public double evaluate(final Plan plan) {
		int numberOfPreferences = plan.getPreferences().size();
		if (numberOfPreferences < 1) {
			return 1;
		}
		int fulfilledPreferences = 0;
		for (ModulePreference preference : plan.getPreferences()) {
			Module module = preference.getModule();
			if (plan.getPreferenceForModule(module) != null) {
				fulfilledPreferences++;
			}
		}
		return ((double) fulfilledPreferences)/((double) numberOfPreferences);
	}
};
