// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Wertet alle Teilzielfunktionen erst ab der Überschreitung des Schwellwertes.
 * Mittelmäßige Studienpläne können so auf sehr schlechte Werte gesetzt werden.
 * Bessere Studienpläne heben sich so stärker heraus.
 */
public class ThresholdObjectiveFunction extends ObjectiveFunction {
	private final double threshold;

	/**
	 * Setzt den Schwellwert auf 0.5
	 */
	public ThresholdObjectiveFunction() {
		threshold = 0.5d;
	}

	/**
	 * Setzt den Schwellwert auf den Angegebenen Wert
	 * 
	 * @param threshold
	 */
	public ThresholdObjectiveFunction(final int threshold) {
		this.threshold = threshold;
	}

	/*
	 * Alle Zielfunktionen werden, wenn sie unter einem Schwellwert sind als
	 * "worst case" gewertet erhalten also die Bewertung 0.
	 */
	@Override
	public double evaluate(final Plan plan) {
		// TODO Auto-generated method stub
		return 0;
	}
};
