// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.objectivefunction;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/************************************************************/
/**
 * Considers the evaluation of all sub-functions only when they attain the threshold.
 * This class sees that the average evaluated plans would be low evaluated and the better 
 * ones would get a better evaluation.
 */
public class ThresholdObjectiveFunction extends AverageObjectiveFunction {
	
	private final double threshold;

	/**
	 * Sets the threshold with the value 0.5
	 */
	public ThresholdObjectiveFunction() {
		threshold = 0.5d;
	}

	/**
	 * Sets the threshold with the value given
	 * 
	 * @param threshold the threshold
	 */
	public ThresholdObjectiveFunction(final double threshold) {
		this.threshold = threshold;
	}
	
	@Override
	public double evaluate(final Plan plan) {
		double val = super.evaluate(plan);
		if (val < this.threshold) {
			val = 0;
		}
		return val;
	}
};
