// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.storage;


/************************************************************/
/**
 * 
 */
public class Sync {

	/**
	 * 
	 * @param method 
	 * @param model 
	 * @param options 
	 */
	public void OAuthSync(String method, Object model, Object options) {
	}

	/**
	 * 
	 * @param method 
	 * @param model 
	 * @param options 
	 */
	public void CookieSync(String method, Object model, Object options) {
	}
};
