// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.stream.Collectors;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import edu.kit.informatik.studyplan.server.model.moduledata.Field;
import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.moduledata.RuleGroup;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraint;
import edu.kit.informatik.studyplan.server.model.userdata.VerificationState;
import edu.kit.informatik.studyplan.server.rest.resources.json.JsonModule;

/************************************************************/
/**
 * Die Klasse VerificationResult ist das Ergebins einer Verifizierung.
 */
public class VerificationResult {
	/**
	 * VerificationResult enthält ein Array violations vom Typ ModuleConstraint.
	 * In diesem werden verletzte Modulconstraints gespeichert.
	 */
	@JsonProperty("violations")
	private Collection<ModuleConstraint> violations;
	@JsonIgnore
	private Collection<Field> fieldViolations;
	@JsonProperty("rule-group-violations")
	private Collection<RuleGroup> ruleGroupViolations;
	@JsonIgnore
	private Collection<Module> compulsoryViolations;
	@JsonIgnore
	private boolean correct;
	
	public VerificationResult () {
		violations = new HashSet<ModuleConstraint>();
		fieldViolations = new ArrayList<Field>();
		ruleGroupViolations = new ArrayList<RuleGroup>();
		compulsoryViolations = new ArrayList<Module>();
	}

	/**
	 * Gibt die verletzten Modul-Constraints zurück.
	 * 
	 * @return die verletzten Modul-Constraints
	 */
	public Collection<ModuleConstraint> getViolations() {
		return violations;
	}
	
	public Collection<Field> getFieldViolations() {
		return fieldViolations;
	}
	
	public Collection<RuleGroup> getRuleGroupViolations() {
		return ruleGroupViolations;
	}

	/**
	 * @return the compulsoryViolations
	 */
	public Collection<Module> getCompulsoryViolations() {
		return compulsoryViolations;
	}

	/**
	 * is correct prüft anhand von violations, ob der Studienplan erfolgreich
	 * verifiziert wurde.
	 * 
	 * @return zurückgegeben wird false, falls der Studienplan fehlerhaft ist
	 *         und true, wenn er zu einem erfolreichen Studienabschluss führt.
	 */
	public boolean isCorrect() {
		return correct;
	}
	
	public void setCorrect(boolean isCorrect) {
		correct = isCorrect;
	}
	
	@JsonProperty("status")
	public VerificationState getVerificationState() {
		return isCorrect() ? VerificationState.VALID : VerificationState.INVALID;
	}
	
	@JsonProperty("compulsory-violations")
	public List<JsonModule> getCompulsoryViolationsForJson() {
		return getCompulsoryViolations().stream()
				.map(module -> {
					JsonModule jsonModule = new JsonModule();
					jsonModule.setName(module.getName());
					return jsonModule;
				}).collect(Collectors.toList());
	}
	
	@JsonProperty("field-violations")
	public List<FieldSummaryDto> getFieldViolationsForJson() {
		return getFieldViolations().stream()
				.map(field -> new FieldSummaryDto(field))
				.collect(Collectors.toList());
	}
	
	
	public class FieldSummaryDto {
		
		@JsonProperty
		String name;
		
		@JsonProperty("min-ects")
		double minEcts;
		
		public FieldSummaryDto(Field field) {
			this.name = field.getName();
			this.minEcts = field.getMinEcts();
		}
	}
};
