// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.verification;

import java.util.ArrayList;
import java.util.Collection;

import edu.kit.informatik.studyplan.server.model.moduledata.Field;
import edu.kit.informatik.studyplan.server.model.moduledata.RuleGroup;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraint;

/************************************************************/
/**
 * Die Klasse VerificationResult ist das Ergebins einer Verifizierung.
 */
public class VerificationResult {
	/**
	 * VerificationResult enthält ein Array violations vom Typ ModuleConstraint.
	 * In diesem werden verletzte Modulconstraints gespeichert.
	 */
	private Collection<ModuleConstraint> violations;
	private Collection<Field> fieldViolations;
	private Collection<RuleGroup> ruleGroupViolations;
	private boolean correct;
	
	public VerificationResult () {
		violations = new ArrayList<ModuleConstraint>();
		fieldViolations = new ArrayList<Field>();
		ruleGroupViolations = new ArrayList<RuleGroup>();
	}

	/**
	 * Gibt die verletzten Modul-Constraints zurück.
	 * 
	 * @return die verletzten Modul-Constraints
	 */
	public Collection<ModuleConstraint> getViolations() {
		return violations;
	}
	
	public Collection<Field> getFieldViolations() {
		return fieldViolations;
	}
	
	public Collection<RuleGroup> getRuleGroupViolations() {
		return ruleGroupViolations;
	}

	/**
	 * is correct prüft anhand von violations, ob der Studienplan erfolgreich
	 * verifiziert wurde.
	 * 
	 * @return zurückgegeben wird false, falls der Studienplan fehlerhaft ist
	 *         und true, wenn er zu einem erfolreichen Studienabschluss führt.
	 */
	public boolean isCorrect() {
		return correct;
	}
	
	public void setCorrect(boolean isCorrect) {
		correct = isCorrect;
	}
};
