// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.user;

import edu.kit.informatik.studyplan.client.model.modules.ModuleCollection;

/************************************************************/
/**
 * 
 */
public class PassedModuleCollection extends ModuleCollection {

	@Override
	public String url() {
		// TODO Auto-generated method stub
		return null;
	}
};
