// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.user;

import edu.kit.informatik.studyplan.client.model.user.Student;

/************************************************************/
/**
 * 
 */
public class SessionInformation {
	/**
	 * 
	 */
	private String access_token;
	/**
	 * 
	 */
	private boolean loggedIn;
	/**
	 * 
	 */
	private Student student;
	/**
	 * 
	 */
	private static edu.kit.informatik.studyplan.client.model.user.SessionInformation instance;
	/**
	 * 
	 */
	private String state;

	/**
	 * 
	 * @return  
	 */
	public static edu.kit.informatik.studyplan.client.model.user.SessionInformation getInstance() {
		return instance;
	}

	/**
	 * 
	 */
	public void generateState() {
	}
};
