// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.model.user;

import edu.kit.informatik.studyplan.client.model.user.PassedModuleCollection;

/************************************************************/
/**
 * 
 */
public class Student {
	/**
	 * 
	 */
	private PassedModuleCollection passedModules;
	/**
	 * 
	 */
	private String userId;
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String discipline;
	/**
	 * 
	 */
	private String studystartCycle;
	/**
	 * 
	 */
	private int studyStartYear;
};
