// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import edu.kit.informatik.studyplan.server.model.moduledata.ModuleOrientation;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraintType;
import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

/************************************************************/
/**
 * Modelliert eine allgemeine Zusammengehörigkeit von zwei Modulen.
 */
public abstract class LinkModuleConstraintType extends ModuleConstraintType {

	public abstract boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation);

};
