// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraintType;

/************************************************************/
/**
 * 
 */
public class ModuleConstraint {
	/**
	 * 
	 */
	private ModuleConstraintType constraintType;

	/**
	 * 
	 * @return  
	 */
	public Module getFirstModule() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public Module getSecondModule() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public ModuleConstraintType getConstraintType() {
		return constraintType;
	}
};
