// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import edu.kit.informatik.studyplan.server.model.moduledata.ModuleOrientation;
import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

/************************************************************/
/**
 * Modelliert eine Zusammenhangsabhängigkeit zwischen Modulen: <br>
 * Es müssen immer beide Module im Plan enthalten sein.
 */
public class PlanLinkModuleConstraintType extends ModuleConstraintType {

	public boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation) {
		return false;
	}
};
