// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.Filter;
import edu.kit.informatik.studyplan.server.filter.FilterDescriptor;
import edu.kit.informatik.studyplan.server.filter.FilterType;

/************************************************************/
/**
 * 
 */
public abstract class AttributeFilter implements Filter {
	/**
	 * 
	 */
	public FilterDescriptor filterDescriptor;

	/**
	 * 
	 * @return  
	 */
	public abstract FilterDescriptor getDescriptor();

	/**
	 * 
	 * @return  
	 */
	public abstract FilterType getFilterType();
};
