// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

/************************************************************/
/**
 * from jOOQ
 */
public class Condition {
};
