// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.FilterDescriptor;
import edu.kit.informatik.studyplan.client.view.components.RangeFilter;

/************************************************************/
/**
 * 
 */
public final class CreditPointsFilter extends RangeFilter {

	/**
	 * 
	 * @return  
	 */
	public FilterDescriptor getDescriptor() {
		return null;
	}
};
