// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.FilterDescriptor;

/**
 * Repräsentiert einen ECTS-Intervall-Filter.
 */
public final class CreditPointsFilter extends RangeFilter {
	@Override
	public FilterDescriptor getDescriptor() {
		return FilterDescriptor.CREDIT_POINTS;
	}
};
