// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.AttributeFilter;

/************************************************************/
/**
 * 
 */
public class FilterType {
	/**
	 * 
	 */
	public enum Type {
		/**
		 * 
		 */
		RANGE,
		/**
		 * 
		 */
		LIST,
		/**
		 * 
		 */
		CONTAINS;
	};

	/**
	 * 
	 * @param filter 
	 * @return  
	 */
	public String toJsonSpecification(AttributeFilter filter) {
		return null;
	}
};
