// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.Condition;

/**
 * Repräsentiert einen Filter für Module über eine Filterbedingung.
 */
public interface Filter {

	/**
	 * Gibt die Filterbedingung als jOOQ-Condition-Objekt zurück.
	 * @return  die Filterbedingung
	 */
	public Condition getCondition();
};
