// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.AttributeFilter;
import edu.kit.informatik.studyplan.server.rest.JSONObject;

/************************************************************/
/**
 * 
 */
public class FilterDescriptor {
	/**
	 * 
	 */
	public enum Descriptor {
		/**
		 * 
		 */
		CREDIT_POINTS,
		/**
		 * 
		 */
		CATEGORY,
		/**
		 * 
		 */
		CYCLE_TYPE,
		/**
		 * 
		 */
		TYPE,
		/**
		 * 
		 */
		DISCIPLINE,
		/**
		 * 
		 */
		COMPULSORY,
		/**
		 * 
		 */
		NAME;
	};

	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private String attributeName;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private String defaultJsonValue;
	/**
	 * 
	 */
	private String tooltip;
	/**
	 * 
	 */
	private AttributeFilter attributeFilter;

	/**
	 * //jOOQ
	 * @return  
	 */
	public Object[] toField() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public JSONObject toJson() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public int id() {
		return id;
	}

	/**
	 * 
	 * @return  
	 */
	public AttributeFilter attributeFilter() {
		return attributeFilter;
	}

	/**
	 * 
	 * @return  
	 */
	public String attributeName() {
		return attributeName;
	}

	/**
	 * 
	 * @return  
	 */
	public String name() {
		return attributeName;
	}

	/**
	 * 
	 * @return  
	 */
	public JSONObject defaultJsonValue() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public String tooltip() {
		return attributeName;
	}
};
