// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.filter;

import edu.kit.informatik.studyplan.server.filter.Condition;

/************************************************************/
/**
 * 
 */
public interface Filter {

	/**
	 * 
	 * @return  
	 */
	public Condition getCondition();
};
