// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view;

import edu.kit.informatik.studyplan.client.model.backbone.BackboneView;
import edu.kit.informatik.studyplan.client.model.user.SessionInformation;
import edu.kit.informatik.studyplan.client.view.components.NotificationCentre;

/************************************************************/
/**
 * 
 */
public class MainView {
	/**
	 * 
	 */
	private SessionInformation sessionInformation;
	/**
	 * 
	 */
	private BackboneView header;
	/**
	 * 
	 */
	private BackboneView content;
	/**
	 * 
	 */
	private NotificationCentre notificationCentre;

	/**
	 * 
	 * @param header 
	 * @param options 
	 */
	public void setHeader(BackboneView header, Object options) {
	}

	/**
	 * 
	 * @param content 
	 * @param options 
	 */
	public void setContent(BackboneView content, Object options) {
	}
};
