// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.view.components.ComparisonView;

/************************************************************/
/**
 * 
 */
public class ComparisonPage {
	/**
	 * 
	 */
	private ComparisonView comparisonView;
};
