// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.user.SessionInformation;

/************************************************************/
/**
 * Klasse, welche den Header der Seite kapselt
 */
public class Header {
    /**
     * Das SessionInformation Objekt, welches zur Anzeige des Headers benötigt
     * wird
     */
    private SessionInformation sessionInformation;
};
