// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.user.SessionInformation;

/************************************************************/
/**
 * 
 */
public class Header {
	/**
	 * 
	 */
	private SessionInformation sessionInformation;
};
