// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

/************************************************************/
/**
 * Klasse, welche die Login-Seite kapselt
 */
public class LoginPage {
};
