// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

/************************************************************/
/**
 * 
 */
public class LoginPage {
};
