// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.plans.PlanCollection;

/************************************************************/
/**
 * 
 */
public class MainPage {
	/**
	 * 
	 */
	private PlanCollection planCollection;

	/**
	 * 
	 */
	public void addPlan() {
	}

	/**
	 * 
	 */
	public void compare() {
	}
};
