// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.plans.PlanCollection;
import edu.kit.informatik.studyplan.client.view.components.uipanel.PlanList;

/************************************************************/
/**
 * Klasse, welche die Hauptseite kapselt
 */
public class MainPage {
    /**
     * Die anzuzeigende Plan Liste
     */
    private PlanList planList;

    /**
     * Methode zum hinzufügen eines Plans
     */
    public void addPlan() {
    }
};
