// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.modules.Module;
import edu.kit.informatik.studyplan.client.view.components.Plan;
import edu.kit.informatik.studyplan.client.view.components.PlanHeadBar;

import backbone.BackboneView;

/************************************************************/
/**
 * Klasse, welche die Plan-Bearbeitungsansicht kapselt
 */
public class PlanEditPage {
    /**
     * Sidebar, welche angezeigt wird (in der Hauptansicht der ModuleFinder)
     */
    private BackboneView sidebar;
    /**
     * Plan, der angezeigt wird
     */
    private Plan plan;
    /**
     * Kopfzeile die angezeigt wird
     */
    private PlanHeadBar headBar;

    /**
     * Methode zum aufrufen einer ModuleInfoSidebar
     * 
     * @param module
     */
    public void showModuleDetails(final Module module) {
    }

    /**
     * Methode zum schließen einer ModuleInfoSidebar
     */
    public void hideModuleDetails() {

    }

};
