// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.modules.Module;
import edu.kit.informatik.studyplan.client.view.components.Plan;
import edu.kit.informatik.studyplan.client.view.components.PlanHeadBar;

import backbone.BackboneView;

/************************************************************/
/**
 * 
 */
public class PlanEditPage {
    /**
     * 
     */
    private BackboneView sidebar;
    /**
     * 
     */
    private Plan plan;
    /**
     * 
     */
    private PlanHeadBar headBar;

    /**
     * 
     * @param module
     */
    public void showModuleDetails(final Module module) {
    }

    /**
     * 
     */
    public void hideModuleDetails() {

    }

    /**
     * 
     */
    public void onChange() {
    }
};
