// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.model.modules.Module;
import edu.kit.informatik.studyplan.client.view.components.ModuleFinder;
import edu.kit.informatik.studyplan.client.view.components.PassedModulePlan;

/************************************************************/
/**
 * Klasse, welche die Profil-Seite kapselt
 */
public class ProfilePage {
    /**
     * Ein Plan mit bestandenen Modulen
     */
    private PassedModulePlan passedModules;
    /**
     * Die ModuleFinder sidebar
     */
    private ModuleFinder sidebar;

    /**
     * Methode zum aufrufen einer ModuleInfoSidebar
     * 
     * @param module
     */
    public void showModuleDetails(final Module module) {
    }

    /**
     * Methode zum schließen einer ModuleInfoSidebar
     */
    public void hideModuleDetails() {

    }

    /**
     * Leitet zurück zur Hauptseite (MainPage) und speichert die Änderungen.
     */
    public void close() {
    }
};
