// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.view.components.ModuleFinder;
import edu.kit.informatik.studyplan.client.view.components.PassedModulePlan;

/************************************************************/
/**
 * 
 */
public class ProfilePage {
	/**
	 * 
	 */
	private PassedModulePlan passedModules;
	/**
	 * 
	 */
	private ModuleFinder sidebar;

	/**
	 * Leitet zurück zur Hauptseite (MainPage) und speichert die Änderungen.
	 */
	public void close() {
	}
};
