// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.view.components.WizardComponent;

/************************************************************/
/**
 * Diese Klasse kapselt die Anzeige von Wizards in einem State-Machine-Pattern.
 * curView wird bei der Initialisierung gesetzt. WizardPage kann deshalb für
 * jedwede Wizards verwendet werden.<br>
 * WizardPage implementiert Backbone.Event, sodass man sich als Observer der
 * WizardPage registrieren kann. Hier kann man auf den "complete"-Event
 * reagieren, welcher bedeutet, dass der Wizard beendet ist.
 */
public class WizardPage {
    /**
     * Der aktuell angezeigte WizardComponent
     */
    public WizardComponent curView;

    /**
     * Methode, welche die nächste Seite des Wizards aufruft oder diesen
     * beendet.
     */
    public void next() {
    }
};
