// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.subview;

import edu.kit.informatik.studyplan.client.view.components.WizardComponent;

/************************************************************/
/**
 * curView wird bei der Initialisierung gesetzt. WizardPage kann deshalb sowohl für die Registrierung als auch für die Generierung verwendet werden.
 */
public class WizardPage {
	/**
	 * 
	 */
	public WizardComponent curView;

	/**
	 * 
	 */
	public void next() {
	}
};
