// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.moduledata.dao;

import edu.kit.informatik.studyplan.server.filter.Filter;
import edu.kit.informatik.studyplan.server.model.moduledata.Category;
import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.moduledata.moduledata.dao.ModuleDao;

/************************************************************/
/**
 * 
 */
class HibernateModuleDao {

	/**
	 * 
	 * @return  
	 * @param filter 
	 * @param start 
	 * @param end 
	 */
	public Module getModulesByFilter(Filter filter, int start, int end) {
		return null;
	}

	/**
	 * 
	 * @param id 
	 * @return  
	 */
	public Module getModuleById(String id) {
		return null;
	}

	/**
	 * 
	 * @return  
	 * @param filter 
	 */
	public Module getModulesByFilter(Filter filter) {
		return null;
	}

	/**
	 * 
	 * @param filter 
	 * @return  
	 */
	public Module getRandomModuleByFilter(Filter filter) {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public Category getCategories() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public Discipline getDisciplines() {
		return null;
	}
};
