// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

import edu.kit.informatik.studyplan.server.generation.standard.Node;

/************************************************************/
/**
 * 
 */
public class NodeWithOutput extends Node {
	/**
	 * 
	 */
	private Node[] subnodes;

	/**
	 * 
	 * @return children-nodes 
	 */
	public Node getSubNodes() {
		return null;
	}
};
