// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;

/************************************************************/
/**
 * 
 */
public abstract class Node {
	/**
	 * 
	 */
	private Module module;
	/**
	 * 
	 */
	private Node[] children;
	/**
	 * 
	 */
	private Node[] parents;

	/**
	 * 
	 * @return parent-moduls 
	 */
	public Node getParents() {
		return null;
	}

	/**
	 */
	public void getModule() {
	}

	/**
	 * 
	 * @return parent-moduls 
	 */
	public Node getChildren() {
		return null;
	}
};
