// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;

/************************************************************/
/**
 * Die abstrakte Klasse Node stellt Knoten des Graphen da.
 */
public abstract class Node {
	/**
	 * Ein Knoten beinhaltet ein Module module, welches er darstellt.
	 */
	private Module module;
	
	/**
	 * Ein Knoten beinhaltet eine Liste parents vom Typ Node, die 
	 * alle Knoten enthält, die Kanten zu diesem Knoten haben.
	 */
	private Node[] parents;
	
	/**
	 * ein innerer Knoten zur Darstellung von parallelen Modulen (Knoten). 
	 */
	private Node subNodes;

	/**
	 * Die Methode getPartens gibt die Liste parents zurück.
	 * @return parent-moduls 
	 */
	public Node[] getParents() {
		return null;
	}


	/**
	 * Die Methode gibt das Modul zurück, welches der Knoten darstellt.
	 * @return Das Modul (Typ Module), welches der Knoten repräsentiert.
	 */
	public Module getModule() {
	  return null;
	}

	
	/**
	 * Die Methode addParent fügt der Liste parents vom Typ node 
	 * den übergebenen node hinzu. 
	 * @param node
	 */
	public void addParent(Node node){
	  
	}
	
	/**
	 * die Methode getSubNodes gibt eventuell enthaltene weitere Knoten zurück.
	 * @return enthaltene Knoten
	 */
	public Node getSubNodes(){
	  return null;
	}
	
	/**
	 * Die Methode addSubNode fügt dem innersten Knoten 
	 * den übergebenen Knoten als inneren Knoten hinzu.
	 * @param node der neue innerste Knoten.
	 */
	public void addSubNode(Node node){
	  
	}
	
};
