// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

import edu.kit.informatik.studyplan.server.generation.standard.Node;

/************************************************************/
/**
 * 
 */
public class NodeWithoutOutput extends Node {
};
