// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.generation.standard;

/************************************************************/
/**
 * 
 */
public class WeightFunction {
};
