// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

import edu.kit.informatik.studyplan.client.model.plans.Plan;
import edu.kit.informatik.studyplan.client.model.system.ProposalInformation;
import edu.kit.informatik.studyplan.client.view.components.uielement.ModuleFinder;
import edu.kit.informatik.studyplan.client.view.components.uipanel.WizardComponent;

/************************************************************/
/**
 * 
 */
public class GenerationWizardComponent2 extends WizardComponent {
    /**
     * Plan für welchen generiert werden soll
     */
    private Plan plan;
    /**
     * Die notwendigen Informationen für die Generierung
     */
    private ProposalInformation information;
    /**
     * Der Modul-Finder mit welchem die Module bewertet werden können.
     */
    private ModuleFinder moduleFinder;

    /**
     * Gibt Objekt vom Typ GenerationWizardComponent3 zurück
     * 
     * @return Objekt vom Typ GenerationWizardComponent3 (dritte Seite des
     *         Wizards)
     */
    public WizardComponent next() {
        return null;
    }

    /**
     * Methode, welche bei Veränderungen des Seiteninhalts aufgerufen wird.
     */
    public void onChange() {
    }
};
