// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.client.view.components.uipanel;

/************************************************************/
/**
 * Sidebar, welche angezeigt wird, wenn ein generierter Plan angezeigt wird.
 */
public class ProposalSidebar {

    /**
     * Methode, welche aufgerufen wird, wenn der Plan gelöscht werden soll
     */
    public void delete() {
    }

    /**
     * Methode, welche aufgerufen wird, wenn der Plan gespeichert werden soll
     */
    public void save() {
    }

    /**
     * Methode, welche aufgerufen wird, wenn der Plan unter anderem Namen
     * gespeichert werden soll
     */
    public void saveAs() {
    }
};
