// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

import java.util.List;

import edu.kit.informatik.studyplan.server.filter.Filter;
import edu.kit.informatik.studyplan.server.model.moduledata.Category;
import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.Module;

/************************************************************/
/**
 * 
 */
public interface ModuleDao {

	/**
	 * 
	 * @param id 
	 * @return  
	 */
	public Module getModuleById(String id);

	/**
	 * 
	 * @return  
	 * @param filter 
	 */
	public Module getModulesByFilter(Filter filter);

	/**
	 * 
	 * @return  
	 * @param filter 
	 * @param start 
	 * @param end 
	 */
	public Module getModulesByFilter(Filter filter, int start, int end);

	/**
	 * 
	 * @param filter 
	 * @return  
	 */
	public Module getRandomModuleByFilter(Filter filter);

	/**
	 * 
	 * @return  
	 */
	public Discipline getDisciplines();

	/**
	 * 
	 * @return  
	 */
	public Category getCategories();
	
	/**
	 * 
	 * @return
	 */
	public List<Category> getSubjects();
};
