// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;


/**
 * Kapselt die für die Filterarchitektur nötigen Module-Attribut-Namen als Stringkonstanten.
 * Diese werden bei der Anwendung der Filter in den {@link ModuleDao}-Methoden für die eindeutige
 * Identifzierung von Module-Eigenschaften benutzt.
 * @see edu.kit.informatik.studyplan.server.filter
 */
public final class ModuleAttributeNames {
	/**
	 * Stringkonstante, die die ECTS-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String CREDIT_POINTS = null;
	/**
	 * Stringkonstante, die die Kategorie-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String CATEGORY = null;
	/**
	 * Stringkonstante, die die Modultyp-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String MODULE_TYPE = null;
	/**
	 * Stringkonstante, die die Turnus-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String CYCLE_TYPE = null;
	/**
	 * Stringkonstante, die die Fachrichtungs-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String DISCIPLINE = null;
	/**
	 * Stringkonstante, die die Wahl-/Pflicht-Veranstaltungs-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String IS_COMPULSORY = null;
	/**
	 * Stringkonstante, die die Modulnamens-Eigenschaft eines Moduls repräsentiert.
	 */
	public static final String NAME = null;
};
