// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;



/************************************************************/
/**
 *
 *   for Filter architecture
 */
public final class ModuleAttributeNames {
    			/**
    			 * 
    			 */
    			public static String CREDIT_POINTS;
    			/**
    			 * 
    			 */
    			public static String CATEGORY;
    			/**
    			 * 
    			 */
    			public static String MODULE_TYPE;
    			/**
    			 * 
    			 */
    			public static String CYCLE_TYPE;
    			/**
    			 * 
    			 */
    			public static String DISCIPLINE;
    			/**
    			 * 
    			 */
    			public static String IS_COMPULSORY;
    			/**
    			 * 
    			 */
    			public static String NAME;
};
