// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.dao;

import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDao;

/************************************************************/
/**
 * Factory zur ModuleDao-Erzeugung
 */
public class ModuleDaoFactory {

	/**
	 * 
	 * @return  
	 */
	public ModuleDao getModuleDao() {
		return null;
	}
};
