// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import org.hibernate.Session;

import edu.kit.informatik.studyplan.server.model.HibernateUtil;
import edu.kit.informatik.studyplan.server.model.userdata.User;

/************************************************************/
/**
 * Ein konkretes UserDao, welches die Datenbankverbindung über Hibernate
 * herstellt.
 */
class HibernateUserDao implements UserDao {

	public void deleteUser(User user) {
		// TODO Auto-generated method stub
	}

	public void updateUser(User user) {
		// TODO Auto-generated method stub

	}

	public User findUser(User user) {
		Session session = HibernateUtil.getUserDataSessionFactory().openSession();
		session.beginTransaction();
		return null;
	}

};
