// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import edu.kit.informatik.studyplan.server.model.userdata.User;
import edu.kit.informatik.studyplan.server.model.userdata.dao.UserDao;

/************************************************************/
/**
 * Ein konkretes UserDao, welches die Datenbankverbindung über Hibernate herstellt.
 */
class HibernateUserDao implements UserDao{

	public void deleteUser(User user) {
		// TODO Auto-generated method stub
	}

	public void updateUser(User user) {
		// TODO Auto-generated method stub
		
	}

	public User findUser(User user) {
		// TODO Auto-generated method stub
		return null;
	}

};
