// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

/************************************************************/
/**
 * Factory zur UserDao-Erzeugung
 */
public class PlanDaoFactory {

	/**
	 * 
	 * @return liefert das für die verwendete Datenbankschnittstelle benötigte
	 *         DAO zurück
	 */
	public static PlanDao getPlanDao() {
		return new HibernatePlanDao();
	}
};
