// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import edu.kit.informatik.studyplan.server.model.userdata.Plan;

/**
 * DataAccessObject for accessing the user database
 * @author NiklasUhl
 */
public interface PlanDao {

	/**
	 * Searches for a plan by it's unique identifiers
	 * 
	 * @return the found plan or <code>null</code> if nothing was found
	 * @param id
	 *            the identifier
	 */
	Plan getPlanById(String id);

	/**
	 * deletes the plan from database
	 * @param plan
	 *            the plan
	 */
	void deletePlan(Plan plan);

	/**
	 * Saves all changes on the plan, or saves a new one if it does not exist yet.
	 * 
	 * @param plan
	 *            the plan
	 * @return the generated identifier for this plan
	 */
	String updatePlan(Plan plan);
};
