// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import java.time.LocalDateTime;

import org.hibernate.Session;

import edu.kit.informatik.studyplan.server.model.HibernateUtil;
import edu.kit.informatik.studyplan.server.model.userdata.User;
import edu.kit.informatik.studyplan.server.model.userdata.authorization.AuthorizationContext;

/************************************************************/
/**
 * Konkrete Implementierung eines Security-Providers, der Hibernate verwendet.
 */
class SecurityProvider extends AbstractSecurityProvider {

	@Override
	public AuthorizationContext generateAuthorizationContext(User user) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public AuthorizationContext getAuthorizationContext(String accessToken) {
		Session session = HibernateUtil.getUserDataSessionFactory().openSession();
		session.beginTransaction();
		AuthorizationContext authorizationContext = session.byId(AuthorizationContext.class).load(accessToken);
		session.getTransaction().commit();
		session.close();
		if (authorizationContext != null) {
			if (authorizationContext.getExpiryDate().isBefore(LocalDateTime.now())) {
				authorizationContext = null;
			}
		}
		return authorizationContext;
	}
};
