// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

/************************************************************/
/**
 * Factory zur UserDao-Erzeugung
 */
public class UserDaoFactory {

	/**
	 * 
	 * @param authorizationContext 
	 * @return liefert das für die verwendete Datenbankschnittstelle benötigte
	 *         DAO zurück
	 */
	public static UserDao getUserDao(AuthorizationContext authorizationContext) {
		return new HibernateUserDao(authorizationContext);
	}
	
};
