// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.moduledata.dao.ModuleDaoFactory;

import javax.persistence.*;

/************************************************************/
/**
 * Modelliert einen Moduleintrag in einem Studienplan
 */
@Entity
@Table(name = "module_entry")
public class ModuleEntry {
	/**
	 * 
	 */
	@Id
	@Column(name = "entry_id")
	private int id;

	@Column(name = "moduleId")
	private String moduleId;

	@Transient
	private Module module;
	/**
	 * 
	 */
	@Column(name = "semester")
	private int semester;

	/**
	 * 
	 * @return gibt das Modul zurück
	 */
	public Module getModule() {
		if (module == null) {
			module = ModuleDaoFactory.getModuleDao().getModuleById(moduleId);
		}
		return module;
	}

	/**
	 * 
	 * @param module
	 *            das Modul
	 */
	public void setModule(Module module) {
		this.moduleId = module.getIdentifier();
		this.module = module;
	}

	/**
	 * 
	 * @return gibt die Nummer des Semesters zurück, dem der Eintrag zugeordnet
	 *         wurde
	 */
	public int getSemester() {
		return semester;
	}

	/**
	 * 
	 * @param semester
	 *            die Semesternummer
	 */
	public void setSemester(int semester) {
		this.semester = semester;
	}
};
