// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import java.util.List;

import edu.kit.informatik.studyplan.server.model.moduledata.Module;
import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;
import edu.kit.informatik.studyplan.server.model.userdata.ModulePreference;
import edu.kit.informatik.studyplan.server.model.userdata.PreferenceType;
import edu.kit.informatik.studyplan.server.model.userdata.User;
import edu.kit.informatik.studyplan.server.model.userdata.VerificationState;

/************************************************************/
/**
 * Modelliert einen Studienplan
 */
public class Plan {
	/**
	 * 
	 */
	private int planId;
	/**
	 * 
	 */
	private String identifier;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private VerificationState state;
	/**
	 * 
	 */
	private int creditPoints;
	/**
	 * 
	 */
	private User user;
	/**
	 * 
	 */
	private List<ModuleEntry> moduleEntries;
	/**
	 * 
	 */
	private List<ModulePreference> modulePreferences;

	/**
	 * Gibt für ein übergebenes Modul die Präferenz zurück. <br>
	 * <code>null</code>, falls keine Präferenz vorhanden
	 * 
	 * @return die Präferenz
	 * @param module
	 *            das Modul
	 */
	public PreferenceType getPreferenceForModule(Module module) {
		return null;
	}

	/**
	 * 
	 * @return gibt die eindeutige Plan-ID zurück
	 */
	public int getPlanId() {
		return 0;
	}

	/**
	 * 
	 * @param planId
	 *            die Plan-ID
	 */
	public void setPlanId(String planId) {
	}

	/**
	 * 
	 * @return gibt den eindeutigen Plan-Identifier zurück
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * 
	 * @param identifier
	 *            der Plan-Identifier
	 */
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	/**
	 * 
	 * @return gibt den Namen des Plans zurück
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @param name
	 *            der Name
	 */
	public void setName(String name) {
	}

	/**
	 * 
	 * @return gibt den Verifizierungsstatus des Plans zurück
	 */
	public VerificationState getVerificationState() {
		return state;
	}

	/**
	 * 
	 * @param verificationState
	 *            der Verifizierungsstatus
	 */
	public void setVerificationState(VerificationState verificationState) {
	}

	/**
	 * 
	 * @return gibt die ECTS-Summe des Plans zurück
	 */
	public int getCreditPoints() {
		return creditPoints;
	}

	/**
	 * 
	 * @param creditPoints
	 *            die ECTS-Summe
	 */
	public void setCreditPoints(int creditPoints) {

	}

	/**
	 * 
	 * @return gibt den Eigentümer des Plans zurück
	 */
	public User getUser() {
		return user;
	}

	/**
	 * 
	 * @param user
	 *            der Eigentümer
	 */
	public void setUser(User user) {
	}

	/**
	 * 
	 * @return gibt alle Moduleinträge des Plans zurück
	 */
	public List<ModuleEntry> getModuleEntries() {
		return null;
	}

	/**
	 * 
	 * @return gibt eine List der Modulpräferenzen zurück
	 */
	public ModulePreference getPreferences() {
		return null;
	}
};
