// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

/************************************************************/
/**
 * Modelliert den Typ einer Modulpräferenz
 */
public enum PreferenceType {
	/**
	 * das Modul wurde positiv bewertet
	 */
	POSITIVE,
	/**
	 * das Modul wurde negativ bewertet
	 */
	NEGATIVE;
};
