// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import edu.kit.informatik.studyplan.server.model.moduledata.CycleType;
import edu.kit.informatik.studyplan.server.model.userdata.SemesterType;

/************************************************************/
/**
 * Modelliert ein Semester
 */
public class Semester {
	/**
	 * 
	 */
	private CycleType semesterType;
	/**
	 * 
	 */
	private int year;

	/**
	 * Berechnet die Anzahl an Semester, die seit diesem Semester vergangen sind
	 * (inkl. aktuelles)
	 * 
	 * @return die Semesterzahl
	 */
	public int getDistanceToCurrentSemester() {
		return year;
	}

	/**
	 * 
	 * @return gibt den Typ des Semester zurück
	 * @see edu.kit.informatik.studyplan.server.model.userdata.SemesterType
	 */
	public SemesterType getSemesterType() {
		return null;
	}

	/**
	 * 
	 * @param semesterType
	 *            der Semestertyp
	 */
	public void setSemesterType(SemesterType semesterType) {
	}

	/**
	 * 
	 * @return gibt das Jahr zurück in dem das Semester begonnen hat
	 */
	public int getYear() {
		return year;
	}

	/**
	 * 
	 * @param year
	 *            das Jahr in dem das Semester begonnen hat
	 */
	public void setYear(int year) {
	}
};
