// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

/************************************************************/
/**
 * Modelliert Semester-Typen
 */
public enum SemesterType {
	/**
	 * Wintersemester
	 */
	WINTER_TERM,
	/**
	 * Sommersemester
	 */
	SUMMER_TERM;
};
