// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata;

import java.security.Principal;
import java.util.List;

import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;
import edu.kit.informatik.studyplan.server.model.userdata.Plan;
import edu.kit.informatik.studyplan.server.model.userdata.Semester;

/************************************************************/
/**
 * Modelliert einen Nutzer.
 */
public class User implements Principal {
	/**
	 * 
	 */
	private int userId;
	/**
	 * 
	 */
	private String userName;
	/**
	 * 
	 */
	private Discipline discipline;
	/**
	 * 
	 */
	private Semester studyStart;
	/**
	 * 
	 */
	private List<ModuleEntry> passedModules;

	/**
	 * 
	 * @return gibt die eindeutige ID des Nutzers zurück
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * 
	 * @param userId
	 *            Wert, auf den die ID gesetzt wird
	 */
	public void setUserId(int userId) {
	}

	/**
	 * 
	 * @return gibt den eindeutigen Nutzernamen zurück
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * 
	 * @param userName
	 *            der Nutzername
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * 
	 * @return gibt den Studiengang zurück
	 */
	public Discipline getDiscipline() {
		return discipline;
	}

	/**
	 * 
	 * @param discipline
	 *            der Studiengang
	 */
	public void setDiscipline(Discipline discipline) {
	}

	/**
	 * 
	 * @return gibt das Semester des Studienstarts zurück
	 */
	public Semester getStudyStart() {
		return studyStart;
	}

	/**
	 * 
	 * @param semester
	 *            das Semester des Studienstarts
	 */
	public void setStudyStart(Semester semester) {
	}

	/**
	 * 
	 * @return gibt eine Liste von Modul-Einträgen der bestandenen Module zurück
	 */
	public List<ModuleEntry> getPassedModules() {
		return null;
	}

	/**
	 * 
	 * @return gibt eine Liste der Studienpläne des Nutzers zurück
	 */
	public List<Plan> getPlans() {
		return null;
	}

	@Override
	public String getName() {
		return userName;
	}
};
