// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * Modelliert eine Modul-Kategorie.
 */
public class Category {
	/**
	 * 
	 */
	private int categoryId;
	/**
	 * 
	 */
	private String name;
	
	private boolean isSubject;

	/**
	 * 
	 * @return  gibt die eindeutige Kategorie-ID zurück
	 */
	public int getCategoryId() {
		return categoryId;
	}

	/**
	 * 
	 * @return  gibt den Namen der Kategorie zurück
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * 
	 * @return gibt zurück ob es sich bei der Kategorie um ein Vertiefungsfach handelt
	 */
	public boolean isSubject() {
		return isSubject;
	}
};
