// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * 
 */
public class Category {
	/**
	 * 
	 */
	private int categoryId;
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @return  
	 */
	public int getCategoryId() {
		return categoryId;
	}

	/**
	 * 
	 * @return  
	 */
	public String getName() {
		return name;
	}
};
