// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * 
 */
public enum CycleType {
	/**
	 * 
	 */
	WINTER_TERM,
	/**
	 * 
	 */
	SUMMER_TERM,
	/**
	 * 
	 */
	BOTH;
};
