// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * 
 */
public class Discipline {
	/**
	 * 
	 */
	private int disciplineId;
	/**
	 * 
	 */
	private String description;

	/**
	 * 
	 * @return  
	 */
	public int getDisciplineId() {
		return disciplineId;
	}

	/**
	 * 
	 * @return  
	 */
	public String getDescription() {
		return description;
	}
};
