// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * 
 */
public enum ModuleOrientation {
	/**
	 * 
	 */
	LEFT_TO_RIGHT,
	/**
	 * 
	 */
	RIGHT_TO_LEFT;
};
