// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import edu.kit.informatik.studyplan.server.model.moduledata.ModuleType;

/************************************************************/
/**
 * Modelliert eine Modulbeschreibung <br>
 * Eine Modulbeschreibung kann mehreren Modulen zugeordnet sein
 */
public class ModuleDescription {
	/**
	 * 
	 */
	private int descriptionId;
	/**
	 * 
	 */
	private String descriptionText;
	/**
	 * 
	 */
	private String lecturer;

	/**
	 * 
	 * @return gibt die eindeutige Beschreibungs-ID zurück
	 */
	public int getDescriptionId() {
		return descriptionId;
	}

	/**
	 * 
	 * @return gibt den Beschreibungstext zurück
	 */
	public String getDescriptionText() {
		return descriptionText;
	}

	/**
	 * 
	 * @return gbit den Dozenten zurück
	 */
	public String getLecturer() {
		return descriptionText;
	}

	/**
	 * 
	 * @return gibt den Modul-Typ zurück
	 */
	public ModuleType getModuleType() {
		return null;
	}
};
