// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import edu.kit.informatik.studyplan.server.model.moduledata.Category;
import edu.kit.informatik.studyplan.server.model.moduledata.CycleType;
import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.ModuleDescription;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraint;

/************************************************************/
/**
 * 
 */
public class Module {
	/**
	 * 
	 */
	private ModuleConstraint[] moduleConstraints;
	/**
	 * 
	 */
	private Category[] categories;
	/**
	 * 
	 */
	private ModuleDescription moduleDescription;
	/**
	 * 
	 */
	private Discipline discipline;
	/**
	 * 
	 */
	private String moduleId;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private int creditPoints;
	/**
	 * 
	 */
	private CycleType cycleType;
	/**
	 * 
	 */
	private boolean compulsory;

	/**
	 * 
	 * @return  
	 */
	public String getModuleId() {
		return moduleId;
	}

	/**
	 * 
	 * @return  
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @return  
	 */
	public int getCreditPoints() {
		return 0;
	}

	/**
	 * 
	 * @return  
	 */
	public CycleType getCycleType() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public boolean isCompulsory() {
		return false;
	}

	/**
	 * 
	 * @return  
	 */
	public Discipline getDiscipline() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public ModuleDescription getModuleDescription() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public ModuleConstraint getConstraints() {
		return null;
	}

	/**
	 * 
	 * @return  
	 */
	public Category getCategories() {
		return null;
	}
};
