// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * Modelliert einen Modultyp, wie beispielsweise Vorlesung, Seminar, etc.
 */
public class ModuleType {
	/**
	 * 
	 */
	private int typeId;
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @return gibt die eindeutige Typ-ID zurück 
	 */
	public int getTypeId() {
		return typeId;
	}

	/**
	 * 
	 * @return gibt den Namen des Typs zurück
	 */
	public String getName() {
		return name;
	}
};
