// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import java.util.List;

import edu.kit.informatik.studyplan.server.model.moduledata.Category;
import edu.kit.informatik.studyplan.server.model.moduledata.CycleType;
import edu.kit.informatik.studyplan.server.model.moduledata.Discipline;
import edu.kit.informatik.studyplan.server.model.moduledata.ModuleDescription;
import edu.kit.informatik.studyplan.server.model.moduledata.constraint.ModuleConstraint;

/************************************************************/
/**
 * Modelliert ein Modul
 */
public class Module {
	/**
	 * 
	 */
	private List<ModuleConstraint> moduleConstraints;
	/**
	 * 
	 */
	private List<Category> categories;
	/**
	 * 
	 */
	private ModuleDescription moduleDescription;
	/**
	 * 
	 */
	private Discipline discipline;
	/**
	 * 
	 */
	private int moduleId;
	/**
	 * 
	 */
	private String identifier;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private int creditPoints;
	/**
	 * 
	 */
	private CycleType cycleType;
	/**
	 * 
	 */
	private boolean compulsory;

	/**
	 * 
	 * @return gibt die eindeutige Modul-ID zurück
	 */
	public int getModuleId() {
		return moduleId;
	}
	
	/**
	 * 
	 * @return gibt den eindeutigen Identifier-String zurück
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * 
	 * @return gibt die Modulbezeichnung zurück
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @return gibt die ECTS-Zahl des Moduls zurück
	 */
	public int getCreditPoints() {
		return 0;
	}

	/**
	 * 
	 * @return  gibt den Turnus des Moduls zurück
	 */
	public CycleType getCycleType() {
		return null;
	}

	/**
	 * 
	 * @return  gibt zurück, ob es sich um ein Pflichtmodul handelt
	 */
	public boolean isCompulsory() {
		return false;
	}

	/**
	 * 
	 * @return gibt den Studiengang, dem das Modul angehört, zurück <br>
	 * Ein Modul ist immer eindeutig einem Studiengang zugeordnet. Wird ein Modul
	 * in der Realität für mehrere Studiengänge angeboten, so handelt es sich jeweils
	 * um unterschiedliche Module, denn in einem anderen Studiengang können Modulabhängigkeiten
	 * ggf. varieren.
	 */
	public Discipline getDiscipline() {
		return null;
	}

	/**
	 * 
	 * @return  gibt die Modul-Beschreibung des Moduls zurück
	 */
	public ModuleDescription getModuleDescription() {
		return null;
	}

	/**
	 * 
	 * @return  gibt die Abhängigkeiten des Moduls zu anderen Modulen zurück
	 */
	public List<ModuleConstraint> getConstraints() {
		return null;
	}

	/**
	 * 
	 * @return  gibt die Kategorien, denen das Modul angehört, zurück
	 */
	public List<Category> getCategories() {
		return null;
	}
};
