// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

/************************************************************/
/**
 * 
 */
public class ModuleType {
	/**
	 * 
	 */
	private int typeId;
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @return  
	 */
	public int getTypeId() {
		return typeId;
	}

	/**
	 * 
	 * @return  
	 */
	public String getName() {
		return name;
	}
};
