// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata;

import edu.kit.informatik.studyplan.server.model.moduledata.ModuleType;

/************************************************************/
/**
 * 
 */
public class ModuleDescription {
	/**
	 * 
	 */
	private int descriptionId;
	/**
	 * 
	 */
	private String descriptionText;
	/**
	 * 
	 */
	private String lecturer;

	/**
	 * 
	 * @return  
	 */
	public int getDescriptionId() {
		return descriptionId;
	}

	/**
	 * 
	 * @return  
	 */
	public String getDescriptionText() {
		return descriptionText;
	}

	/**
	 * 
	 * @return  
	 */
	public String getLecturer() {
		return descriptionText;
	}

	/**
	 * 
	 * @return  
	 */
	public ModuleType getModuleType() {
		return null;
	}
};
