// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

/************************************************************/
/**
 * Modelliert eine zeitliche Abhängigkeit zwischen zwei Modulen:<br>
 * Die beiden Module können nicht im gleichen Semester belegt werden, da die
 * Veranstaltung zur gleichen Zeit stattfindet.
 */
@Entity
@DiscriminatorValue(value = "overlapping")
public class OverlappingModuleConstraintType extends ModuleConstraintType {

	@Override
	public boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation) {
		return first.getSemester() != second.getSemester();
	}
};
