// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

/************************************************************/
/**
 * Modelliert eine Zusammenhangsabhängigkeit zwischen Modulen: <br>
 * Es müssen immer beide Module im Plan enthalten sein.
 */
@Entity
@DiscriminatorValue(value = "plan_link")
public class PlanLinkModuleConstraintType extends ModuleConstraintType {

	@Override
	public boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation) {
		if (first != null && first.isPassed() && second == null) {
			return false;
		}
		if (second != null && second.isPassed() && first == null) {
			return false;
		}
		return first != null && second != null;
	}
};
