// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

/************************************************************/
/**
 * Modelliert eine Zusammenhangsabhängigkeit zwischen Modulen: <br>
 * Es müssen immer beide Module im Plan enthalten sein.
 */
@Entity
@DiscriminatorValue(value = "plan_link")
public class PlanLinkModuleConstraintType extends ModuleConstraintType {

	@Override
	public boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation) {
		return true;
	}
};
