// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.moduledata.constraint;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

import edu.kit.informatik.studyplan.server.model.userdata.ModuleEntry;

/************************************************************/
/**
 * Modelliert eine Zusammenhangsbeziehung zwischen zwei Modulen:<br>
 * Beide Module müssen im gleichen Semester belegt werden.
 */
@Entity
@DiscriminatorValue(value = "semester_link")
public class SemesterLinkModuleConstraintType extends ModuleConstraintType {

	@Override
	public boolean isValid(ModuleEntry first, ModuleEntry second, ModuleOrientation orientation) {
		return first.getSemester() == second.getSemester();
	}
};
