// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package edu.kit.informatik.studyplan.server.model.userdata.dao;

import edu.kit.informatik.studyplan.server.model.userdata.User;
import edu.kit.informatik.studyplan.server.model.userdata.authorization.AuthorizationContext;
import edu.kit.informatik.studyplan.server.model.userdata.dao.AbstractSecurityProvider;

/************************************************************/
/**
 * Konkrete Implementierung eines Security-Providers, der Hibernate verwendet.
 */
class SecurityProvider extends AbstractSecurityProvider {

	@Override
	public AuthorizationContext generateAuthorizationContext(User user) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public AuthorizationContext getAuthorizationContext(String accessToken) {
		// TODO Auto-generated method stub
		return null;
	}
};
